NOTE: atomisp into staging
- moved intel-aero atomisp drivers into staging

Note that intel_soc_pmic_{readb,writeb} is introduced with intel-aero
whiskeycove patch. So, unless it's applied, the current (intel-aero
version) atomisp_gmin_platform.c does not build:

        drivers/staging/media/atomisp/platform/atomisp_gmin_platform.c: In function ‘axp_regulator_set’:
        drivers/staging/media/atomisp/platform/atomisp_gmin_platform.c:471:15: error: implicit declaration of function ‘intel_soc_pmic_writeb’ [-Werror=implicit-function-declaration]
          471 |         ret = intel_soc_pmic_writeb(sel_reg, setting);
              |               ^~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/platform/atomisp_gmin_platform.c:474:15: error: implicit declaration of function ‘intel_soc_pmic_readb’ [-Werror=implicit-function-declaration]
          474 |         val = intel_soc_pmic_readb(ctrl_reg);
              |               ^~~~~~~~~~~~~~~~~~~~
        cc1: some warnings being treated as errors

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>