(port-to-v5.7) atomisp: intel_mid_pcihelpers: use cpu_latency_qos_*() instead of pm_qos_update*()
Ref: 8d564cd28cfc ("media: atomisp: use cpu_latency_qos_*() instead of pm_qos_update*()")

Fixes:

        drivers/staging/media/atomisp/platform/intel_mid_pcihelpers.c: In function ‘intel_mid_msgbus_init’:
        drivers/staging/media/atomisp/platform/intel_mid_pcihelpers.c:48:17: error: implicit declaration of function ‘pm_qos_add_request’; did you mean ‘freq_qos_add_request’? [-Werror=implicit-function-declaration]
           48 |                 pm_qos_add_request(&pm_qos,
              |                 ^~~~~~~~~~~~~~~~~~
              |                 freq_qos_add_request
        drivers/staging/media/atomisp/platform/intel_mid_pcihelpers.c:49:25: error: ‘PM_QOS_CPU_DMA_LATENCY’ undeclared (first use in this function)
           49 |                         PM_QOS_CPU_DMA_LATENCY,
              |                         ^~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/platform/intel_mid_pcihelpers.c:49:25: note: each undeclared identifier is reported only once for each function it appears in
        drivers/staging/media/atomisp/platform/intel_mid_pcihelpers.c: In function ‘intel_mid_dw_i2c_acquire_ownership’:
        drivers/staging/media/atomisp/platform/intel_mid_pcihelpers.c:229:17: error: implicit declaration of function ‘pm_qos_update_request’; did you mean ‘freq_qos_update_request’? [-Werror=implicit-function-declaration]
          229 |                 pm_qos_update_request(&pm_qos, CSTATE_EXIT_LATENCY_C1 - 1);
              |                 ^~~~~~~~~~~~~~~~~~~~~
              |                 freq_qos_update_request

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 4117e3884946f00f49d86757e1e85a10e84c8f89)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>