(TEMP) (port-to-v5.4) (atomisp) media: v4l2-ctrls: adapt functions to v5.4
In accordance with commit
- c41e9cff704a ("media: v4l2-ctrls: support g/s_ext_ctrls for requests")
  added on v4.20
- 173f6eacc8a8 ("media: v4l: ctrls: Add debug messages")
  added on v5.4

This commit depends on 29c600ac5ae9 ("(TEMP) [media] v4l2-subdev.h:
resurrect the deprecated control subdev ops for now").

Addresses like:

        drivers/media/v4l2-core/v4l2-ctrls.c: In function ‘v4l2_subdev_g_ext_ctrls’:
        drivers/media/v4l2-core/v4l2-ctrls.c:3617:51: error: passing argument 2 of ‘v4l2_g_ext_ctrls’ from incompatible pointer type [-Werror=incompatible-pointer-types]
         3617 |         return v4l2_g_ext_ctrls(sd->ctrl_handler, cs);
              |                                                   ^~
              |                                                   |
              |                                                   struct v4l2_ext_controls *
        drivers/media/v4l2-core/v4l2-ctrls.c:3567:74: note: expected ‘struct video_device *’ but argument is of type ‘struct v4l2_ext_controls *’
         3567 | int v4l2_g_ext_ctrls(struct v4l2_ctrl_handler *hdl, struct video_device *vdev,
              |                                                     ~~~~~~~~~~~~~~~~~~~~~^~~~
        drivers/media/v4l2-core/v4l2-ctrls.c:3617:16: error: too few arguments to function ‘v4l2_g_ext_ctrls’
         3617 |         return v4l2_g_ext_ctrls(sd->ctrl_handler, cs);
              |                ^~~~~~~~~~~~~~~~
        drivers/media/v4l2-core/v4l2-ctrls.c:3567:5: note: declared here
         3567 | int v4l2_g_ext_ctrls(struct v4l2_ctrl_handler *hdl, struct video_device *vdev,
              |     ^~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>