(build-fix) misc: tspdrv: fix build errors
Fixes the following two build errors:

    In file included from drivers/misc/tspdrv/tspdrv.c:43:0:
    drivers/misc/tspdrv/tspdrv.h:90:2: warning: #warning "************ __KERNEL__ ************" [-Wcpp]
     #warning "************ __KERNEL__ ************"
      ^
    In file included from drivers/misc/tspdrv/tspdrv.c:52:0:
    drivers/misc/tspdrv/ImmVibeSPI.c:30:2: warning: #warning ********* Compiling SPI for DRV2604 using LRA actuator ************ [-Wcpp]
     #warning ********* Compiling SPI for DRV2604 using LRA actuator ************
      ^
    drivers/misc/tspdrv/ImmVibeSPI.c:31:2: warning: #warning *********** Customized version for Xiaomi M3 ********** [-Wcpp]
     #warning *********** Customized version for Xiaomi M3 **********
      ^
    In file included from drivers/misc/tspdrv/tspdrv.c:52:0:
    drivers/misc/tspdrv/ImmVibeSPI.c: In function ‘drv2604_read_reg’:
    drivers/misc/tspdrv/ImmVibeSPI.c:615:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
      unsigned char data;
      ^
    In file included from include/linux/printk.h:244:0,
                     from include/linux/kernel.h:13,
                     from /home/kitakar5525/WorkingDirectory/kernel/linux-kernel_kitakar5525-git/arch/x86/include/asm/percpu.h:44,
                     from /home/kitakar5525/WorkingDirectory/kernel/linux-kernel_kitakar5525-git/arch/x86/include/asm/preempt.h:5,
                     from include/linux/preempt.h:20,
                     from include/linux/spinlock.h:50,
                     from include/linux/seqlock.h:35,
                     from include/linux/time.h:5,
                     from include/linux/stat.h:18,
                     from include/linux/module.h:10,
                     from drivers/misc/tspdrv/tspdrv.c:34:
    include/linux/dynamic_debug.h:64:16: error: implicit declaration of function ‘KBUILD_STR’ [-Werror=implicit-function-declaration]
      static struct _ddebug  __aligned(8)   \
                    ^
    include/linux/dynamic_debug.h:76:2: note: in expansion of macro ‘DEFINE_DYNAMIC_DEBUG_METADATA’
      DEFINE_DYNAMIC_DEBUG_METADATA(descriptor, fmt);  \
      ^
    include/linux/printk.h:250:2: note: in expansion of macro ‘dynamic_pr_debug’
      dynamic_pr_debug(fmt, ##__VA_ARGS__)
      ^
    drivers/misc/tspdrv/ImmVibeSPI.c:635:2: note: in expansion of macro ‘pr_debug’
      pr_debug("drv2604 read addr:0x%x reg:0x%x data:0x%x res:%d",
      ^
    <command-line>:0:27: error: ‘tspdrv’ undeclared (first use in this function)
    include/linux/dynamic_debug.h:66:14: note: in expansion of macro ‘KBUILD_MODNAME’
       .modname = KBUILD_MODNAME,   \
                  ^
    include/linux/dynamic_debug.h:76:2: note: in expansion of macro ‘DEFINE_DYNAMIC_DEBUG_METADATA’
      DEFINE_DYNAMIC_DEBUG_METADATA(descriptor, fmt);  \
      ^
    include/linux/printk.h:250:2: note: in expansion of macro ‘dynamic_pr_debug’
      dynamic_pr_debug(fmt, ##__VA_ARGS__)
      ^
    drivers/misc/tspdrv/ImmVibeSPI.c:635:2: note: in expansion of macro ‘pr_debug’
      pr_debug("drv2604 read addr:0x%x reg:0x%x data:0x%x res:%d",
      ^
    <command-line>:0:27: note: each undeclared identifier is reported only once for each function it appears in
    include/linux/dynamic_debug.h:66:14: note: in expansion of macro ‘KBUILD_MODNAME’
       .modname = KBUILD_MODNAME,   \
                  ^
    include/linux/dynamic_debug.h:76:2: note: in expansion of macro ‘DEFINE_DYNAMIC_DEBUG_METADATA’
      DEFINE_DYNAMIC_DEBUG_METADATA(descriptor, fmt);  \
      ^
    include/linux/printk.h:250:2: note: in expansion of macro ‘dynamic_pr_debug’
      dynamic_pr_debug(fmt, ##__VA_ARGS__)
      ^
    drivers/misc/tspdrv/ImmVibeSPI.c:635:2: note: in expansion of macro ‘pr_debug’
      pr_debug("drv2604 read addr:0x%x reg:0x%x data:0x%x res:%d",
      ^
    In file included from drivers/misc/tspdrv/tspdrv.c:52:0:
    drivers/misc/tspdrv/ImmVibeSPI.c: In function ‘vibrator_enable’:
    drivers/misc/tspdrv/ImmVibeSPI.c:732:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
      char mode;
      ^
    drivers/misc/tspdrv/tspdrv.c: At top level:
    drivers/misc/tspdrv/ImmVibeSPI.c:602:13: warning: ‘drv2604_set_go_bit’ defined but not used [-Wunused-function]
     static void drv2604_set_go_bit(char val)
                 ^
    drivers/misc/tspdrv/ImmVibeSPI.c:894:30: warning: ‘info’ defined but not used [-Wunused-variable]
     static struct i2c_board_info info = {
                                  ^
    cc1: some warnings being treated as errors
    make[3]: *** [scripts/Makefile.build:309: drivers/misc/tspdrv/tspdrv.o] Error 1
    make[2]: *** [scripts/Makefile.build:455: drivers/misc/tspdrv] Error 2
    make[1]: *** [scripts/Makefile.build:455: drivers/misc] Error 2
    make[1]: *** Waiting for unfinished jobs....

TODO: why this fix is required?

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>