(aero-wcove-fix) power_supply: add back removed members of power_supply_property
The commit 3610c8f08c93 ("pmic: intel: port whiskey cove driver")
removed some members of power_supply_property, which breaks at least
max17042_battery driver build.

Fixes the following build error:

        drivers/power/max17042_battery.c:92:9: error: ‘POWER_SUPPLY_PROP_TEMP_MIN’ undeclared here (not in a function); did you mean ‘POWER_SUPPLY_PROP_TEMP_AMBIENT’?
           92 |         POWER_SUPPLY_PROP_TEMP_MIN,
              |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
              |         POWER_SUPPLY_PROP_TEMP_AMBIENT
        drivers/power/max17042_battery.c:93:9: error: ‘POWER_SUPPLY_PROP_TEMP_MAX’ undeclared here (not in a function); did you mean ‘POWER_SUPPLY_PROP_TEMP’?
           93 |         POWER_SUPPLY_PROP_TEMP_MAX,
              |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
              |         POWER_SUPPLY_PROP_TEMP

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit b7ce68d3a4dc18edfb021b8c8c663b8507969ab9)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 524fde290ebc994b99842fc1cb773a2e3a269311)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>