atomisp: pci: css: avoid va_*() redefined error
What's happening?

        In file included from ./include/linux/kernel.h:5,
                         from ./include/linux/delay.h:22,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/platform_support.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/isp_param/interface/ia_css_isp_param_types.h:19,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/binary/interface/ia_css_binary.h:61,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:23,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        ./include/linux/stdarg.h:6: error: "va_start" redefined [-Werror]
            6 | #define va_start(v, l)  __builtin_va_start(v, l)
              |
        In file included from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:21,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:47: note: this is the location of the previous definition
           47 | #define va_start(v,l)   __builtin_va_start(v,l)
              |
        In file included from ./include/linux/kernel.h:5,
                         from ./include/linux/delay.h:22,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/platform_support.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/isp_param/interface/ia_css_isp_param_types.h:19,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/binary/interface/ia_css_binary.h:61,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:23,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        ./include/linux/stdarg.h:8: error: "va_arg" redefined [-Werror]
            8 | #define va_arg(v, T)    __builtin_va_arg(v, T)
              |
        In file included from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:21,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:49: note: this is the location of the previous definition
           49 | #define va_arg(v,l)     __builtin_va_arg(v,l)
              |
        In file included from ./include/linux/kernel.h:5,
                         from ./include/linux/delay.h:22,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/platform_support.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/isp_param/interface/ia_css_isp_param_types.h:19,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/binary/interface/ia_css_binary.h:61,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:23,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        ./include/linux/stdarg.h:9: error: "va_copy" redefined [-Werror]
            9 | #define va_copy(d, s)   __builtin_va_copy(d, s)
              |
        In file included from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:21,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:52: note: this is the location of the previous definition
           52 | #define va_copy(d,s)    __builtin_va_copy(d,s)
              |

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 78091b2cd8750ba62bf103097d0da33bb75ba10e)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit f5635f355ecb20004bd75e7ec1332cd50131fa34)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>