(port-to-v5.8) atomisp: (mmap locking API) convert mmap_sem call sites
Picked changes for atomisp from commit 89154dd5313f ("mmap locking API:
convert mmap_sem call sites missed by coccinelle").

Also applied the same changes for the parts not exist on the upstream
atomisp.

Fixes:

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c: In function ‘alloc_user_pages’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1096:33: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
         1096 |         down_read(&current->mm->mmap_sem);
              |                                 ^~~~~~~~
              |                                 mmap_base
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1098:31: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
         1098 |         up_read(&current->mm->mmap_sem);
              |                               ^~~~~~~~
              |                               mmap_base
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1119:41: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
         1119 |                 down_read(&current->mm->mmap_sem);
              |                                         ^~~~~~~~
              |                                         mmap_base
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1123:39: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
         1123 |                 up_read(&current->mm->mmap_sem);
              |                                       ^~~~~~~~
              |                                       mmap_base

(cherry picked from commit bcec9201540c2ef870d11ad47a1ca6e7aa0da04c)
[ Conflicts:
	drivers/staging/media/atomisp/pci/atomisp2/hmm/hmm_bo.c]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>