(TEMP) (revert-for->=-v5.0) Revert "timekeeping: remove timespec_add/timespec_del"
This reverts commit 437e78d3fd6d35e6d56230962e6d03bb5dcda7f6.

There are many users of them:

        ./i2c/ov8830.h:	struct timespec focus_time;	/* Time when focus was last time set */
        ./i2c/atomisp-ov883x.c:		static const struct timespec move_time = {
        ./i2c/atomisp-ov883x.c:		struct timespec current_time, finish_time, delta_time;
        ./i2c/imx/dw9718.c:	static const struct timespec move_time = {
        ./i2c/imx/dw9718.c:	struct timespec current_time, finish_time, delta_time;
        ./i2c/imx/ad5816g.h:	struct timespec timestamp_t_focus_abs;
        ./i2c/imx/ad5816g.h:	struct timespec focus_time;	/* Time when focus was last time set */
        ./i2c/imx/dw9714.c:	struct timespec temptime;
        ./i2c/imx/dw9714.c:	const struct timespec timedelay = {
        ./i2c/imx/dw9714.h:	struct timespec timestamp_t_focus_abs;
        ./i2c/imx/dw9714.h:	struct timespec focus_time;	/* Time when focus was last time set */
        ./i2c/imx/dw9719.c:	static const struct timespec move_time = {
        ./i2c/imx/dw9719.c:	struct timespec current_time, finish_time, delta_time;
        ./i2c/imx/ad5816g.c:	struct timespec temptime;
        ./i2c/imx/ad5816g.c:	const struct timespec timedelay = {
        ./i2c/imx/dw9719.h:	struct timespec timestamp_t_focus_abs;
        ./i2c/imx/dw9719.h:	struct timespec focus_time;	/* Time when focus was last time set */
        ./i2c/imx/drv201.c:	struct timespec temptime;
        ./i2c/imx/drv201.c:	const struct timespec timedelay = {
        ./i2c/imx/drv201.h:	struct timespec timestamp_t_focus_abs;
        ./i2c/imx/drv201.h:	struct timespec focus_time;	/* Time when focus was last time set */
        ./i2c/imx/dw9718.h:	struct timespec timestamp_t_focus_abs;
        ./i2c/imx/dw9718.h:	struct timespec focus_time;	/* Time when focus was last time set */
        ./i2c/micam/dw9761.c:	static const struct timespec move_time = {
        ./i2c/micam/dw9761.c:	struct timespec current_time, finish_time, delta_time;
        ./i2c/micam/dw9761.h:	struct timespec timestamp_t_focus_abs;
        ./i2c/micam/dw9761.h:	struct timespec focus_time;	/* Time when focus was last time set */
        ./i2c/micam/ov5693.h:	struct timespec timestamp_t_focus_abs;
        ./i2c/micam/atomisp-ov5693.c:	struct timespec temptime;
        ./i2c/micam/atomisp-ov5693.c:	const struct timespec timedelay = {
        ./pci/atomisp_driver/atomisp_cmd.c:	struct timespec ts;

Let's convert them later.

Addresses like:

        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c: In function ‘ov5693_q_focus_status’:
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:1256:20: error: implicit declaration of function ‘timespec_sub’; did you mean ‘timespec64_sub’? [-Werror=implicit-function-declaration]
         1256 |         temptime = timespec_sub(temptime, (dev->timestamp_t_focus_abs));
              |                    ^~~~~~~~~~~~
              |                    timespec64_sub

        drivers/staging/media/atomisp/i2c/imx/dw9718.c: In function ‘dw9718_q_focus_status’:
        drivers/staging/media/atomisp/i2c/imx/dw9718.c:196:23: error: implicit declaration of function ‘timespec_add’; did you mean ‘timespec64_add’? [-Werror=implicit-function-declaration]
          196 |         finish_time = timespec_add(dw9718_dev.focus_time, move_time);
              |                       ^~~~~~~~~~~~
              |                       timespec64_add
        drivers/staging/media/atomisp/i2c/imx/dw9718.c:196:23: error: incompatible types when assigning to type ‘struct timespec’ from type ‘int’
        drivers/staging/media/atomisp/i2c/imx/dw9718.c:197:22: error: implicit declaration of function ‘timespec_sub’; did you mean ‘timespec64_sub’? [-Werror=implicit-function-declaration]
          197 |         delta_time = timespec_sub(current_time, finish_time);
              |                      ^~~~~~~~~~~~
              |                      timespec64_sub

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>