(FIXME) atomisp: pci: css: avoid va_*() redefined error part2
What's happening?

        In file included from ./include/linux/kernel.h:5,
                         from ./include/linux/delay.h:22,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/platform_support.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_acc_types.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_env.h:21,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_memory_access.h:18,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/isp/kernels/raw_aa_binning/raw_aa_binning_1.0/ia_css_raa.host.c:17:
        ./include/linux/stdarg.h:6: error: "va_start" redefined [-Werror]
            6 | #define va_start(v, l)  __builtin_va_start(v, l)
              |
        In file included from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_env.h:19,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_memory_access.h:18,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/isp/kernels/raw_aa_binning/raw_aa_binning_1.0/ia_css_raa.host.c:17:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:47: note: this is the location of the previous definition
           47 | #define va_start(v,l)   __builtin_va_start(v,l)
              |
        In file included from ./include/linux/kernel.h:5,
                         from ./include/linux/delay.h:22,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/platform_support.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_acc_types.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_env.h:21,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_memory_access.h:18,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/isp/kernels/raw_aa_binning/raw_aa_binning_1.0/ia_css_raa.host.c:17:
        ./include/linux/stdarg.h:8: error: "va_arg" redefined [-Werror]
            8 | #define va_arg(v, T)    __builtin_va_arg(v, T)
              |
        In file included from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_env.h:19,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_memory_access.h:18,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/isp/kernels/raw_aa_binning/raw_aa_binning_1.0/ia_css_raa.host.c:17:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:49: note: this is the location of the previous definition
           49 | #define va_arg(v,l)     __builtin_va_arg(v,l)
              |
        In file included from ./include/linux/kernel.h:5,
                         from ./include/linux/delay.h:22,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/platform_support.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_acc_types.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_env.h:21,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_memory_access.h:18,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/isp/kernels/raw_aa_binning/raw_aa_binning_1.0/ia_css_raa.host.c:17:
        ./include/linux/stdarg.h:9: error: "va_copy" redefined [-Werror]
            9 | #define va_copy(d, s)   __builtin_va_copy(d, s)
              |
        In file included from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_env.h:19,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/ia_css_memory_access.h:18,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/isp/kernels/raw_aa_binning/raw_aa_binning_1.0/ia_css_raa.host.c:17:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:52: note: this is the location of the previous definition
           52 | #define va_copy(d,s)    __builtin_va_copy(d,s)
              |

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit f0fb07eed1d2a5953261be0cde6af3d4d3c58896)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit c560398f3470b5b0738509c5643695adc286a8f8)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 005461481a78f90d7ad01d1fc45195b16f07907e)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 80903bed4baa1edb5f1ca2f16d14ab550302e098)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit ad771f65affd53b926fa7a168f3ce488f1e42d04)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 319d452e318a7f7668321799c0b3a72bf34abad5)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 0c62da754cbadbbd5f357aec0dd48a2d791e1a8e)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 7470dba6f0335f41e29b7ffad7c649e0d01f7476)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>