(port-to-v3.11) atomisp: imx: drop obsolete g_chip_ident
Fixes:

        drivers/staging/media/atomisp/i2c/imx/imx.h:35:10: fatal error: media/v4l2-chip-ident.h: No such file or directory
           35 | #include <media/v4l2-chip-ident.h>
              |          ^~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 41862bbd8303a736bb9944c36e6fc857bc1ac170)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit cfd6f12efa9e15b7c20dbc20375eb67919830035)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 9de123fb7ccb044eeed9fcaac73afc9160d8b5e9)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>