(TEMP) (revert-for->=v5.12) Revert "x86/platform/intel-mid: Drop unused __intel_mid_cpu_chip and Co."
This reverts commit 043698c580f441446a1716ea506ecec90c18093a.

There is a user in atomisp_compat_css20:

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_css20.c: In function ‘atomisp_css_input_set_mode’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_css20.c:2116:29: error: implicit declaration of function ‘intel_mid_identify_cpu’ [-Werror=implicit-function-declaration]
         2116 |                         if (intel_mid_identify_cpu() ==
              |                             ^~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_css20.c:2117:33: error: ‘INTEL_MID_CPU_CHIP_TANGIER’ undeclared (first use in this function)
         2117 |                                 INTEL_MID_CPU_CHIP_TANGIER)
              |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_css20.c:2117:33: note: each undeclared identifier is reported only once for each function it appears in

Revert this commit to preserve the original aero atomisp features for
now.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>