(port-to-v4.5) atomisp: replace media_entity_type() with is_media_entity_v4l2_subdev()
The is_media_entity_v4l2_subdev() is introduced on commit fa17b46a6a01
("[media] media: add macros to check if subdev or V4L2 DMA") on v4.5
series.

Then, the media_entity_type() is removed on commit 687b4209c83e
("[media] media controller: get rid of entity subtype on Kernel")
on v4.5.

Ref:
- mchehab/experimental.git - Mauro's development stuff
  https://git.linuxtv.org/mchehab/experimental.git/commit/?h=yocto_intel_aero_ported_v2&id=2616c5667872506e07ac7b0549ddb049697ff200
  ("media: atomisp: make Yocto's version build with Kernel 5.7")
- 3efdf62c5f68 ("[media] media: use macros to check for V4L2 subdev entities")

Fixes the following build error:

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c: In function ‘isp_subdev_link_setup’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c:1045:32: error: implicit declaration of function ‘media_entity_type’; did you mean ‘media_entity_put’? [-Werror=implicit-function-declaration]
         1045 |         switch (local->index | media_entity_type(remote->entity)) {
              |                                ^~~~~~~~~~~~~~~~~
              |                                media_entity_put

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_csi2.c: In function ‘csi2_link_setup’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_csi2.c:195:37: error: implicit declaration of function ‘media_entity_type’; did you mean ‘media_entity_put’? [-Werror=implicit-function-declaration]
          195 |         u32 result = local->index | media_entity_type(remote->entity);
              |                                     ^~~~~~~~~~~~~~~~~
              |                                     media_entity_put

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit ffd4c257cf0dda37317af155b8e027fafe70f94d)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 62a60615dcf5f24797ab8c2c50dcdec858e6c246)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit ecd4ff8a7c108b9b266fe2bd427cbdb7dc4d6a74)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit d94ec960fd0ea1d362e404c4f08294d3cb53599b)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>