(port-to-v4.5) atomisp: pci: rename the function that create pad links
In accordance with commit 8df00a15817e ("[media] media: rename the
function that create pad links")

Fixes like:

	drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c: In function ‘atomisp_register_entities’:
	drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1053:23: error: implicit declaration of function ‘media_entity_create_link’; did you mean ‘media_entity_setup_link’? [-Werror=implicit-function-declaration]
	 1053 |                 ret = media_entity_create_link(
	      |                       ^~~~~~~~~~~~~~~~~~~~~~~~
	      |                       media_entity_setup_link

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 7d20dfc52f490e85a93cee91a7f53e3ca18b398d)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>