(port-to-v4.17) atomisp: Deprecate pci_get_bus_and_slot()
In accordance with commit 5cf0c37a71da ("PCI: Remove pci_get_bus_and_slot()
function").

The commit message of 67c8d3269266 ("powerpc/via-pmu: Deprecate
pci_get_bus_and_slot()") says:

	> pci_get_bus_and_slot() is restrictive such that it assumes domain=0 as
	> where a PCI device is present. This restricts the device drivers to be
	> reused for other domain numbers.

	> Getting ready to remove pci_get_bus_and_slot() function in favor of
	> pci_get_domain_bus_and_slot().

	> Hard-code the domain number as 0 to match the previous behavior.

So, hard-code the domain number as 0 to match the previous behavior
here also.

Another ref:
- 57b29646bb48 ("drm/i915: Deprecate pci_get_bus_and_slot()")
	> Extract the domain number from drm_device and pass it into
	> pci_get_domain_bus_and_slot() function.

Fixes like:

        drivers/staging/media/atomisp/platform/intel_mid_pcihelpers.c: In function ‘intel_mid_msgbus_init’:
        drivers/staging/media/atomisp/platform/intel_mid_pcihelpers.c:41:20: error: implicit declaration of function ‘pci_get_bus_and_slot’; did you mean ‘pci_get_domain_bus_and_slot’? [-Werror=implicit-function-declaration]
           41 |         pci_root = pci_get_bus_and_slot(0, PCI_DEVFN(0, 0));
              |                    ^~~~~~~~~~~~~~~~~~~~
              |                    pci_get_domain_bus_and_slot
        drivers/staging/media/atomisp/platform/intel_mid_pcihelpers.c:41:18: warning: assignment to ‘struct pci_dev *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
           41 |         pci_root = pci_get_bus_and_slot(0, PCI_DEVFN(0, 0));
              |                  ^

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit d8b87c5e195ab9d050e526c8e6d50133a99c17ab)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>