(port-to-v4.1) atomisp: imx: replace v4l2_subdev_fh by v4l2_subdev_pad_config
In accordance with commit f7234138f14c ("[media] v4l2-subdev: replace
v4l2_subdev_fh by v4l2_subdev_pad_config") added on v4.1-rc1.

While here, fixed indentation where I touched in this commit.

Fixes:

        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2102:51: error: passing argument 1 of ‘v4l2_subdev_get_try_format’ from incompatible pointer type [-Werror=incompatible-pointer-types]
         2102 |                 return v4l2_subdev_get_try_format(fh, pad);
              |                                                   ^~
              |                                                   |
              |                                                   struct v4l2_subdev_fh *
        In file included from drivers/staging/media/atomisp/include/linux/atomisp_platform.h:26,
                         from drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:22:
        include/media/v4l2-subdev.h:770:38: note: expected ‘struct v4l2_subdev *’ but argument is of type ‘struct v4l2_subdev_fh *’
          770 |         fun_name(struct v4l2_subdev *sd,                                \
              |                  ~~~~~~~~~~~~~~~~~~~~^~
        include/media/v4l2-subdev.h:778:1: note: in expansion of macro ‘__V4L2_SUBDEV_MK_GET_TRY’
          778 | __V4L2_SUBDEV_MK_GET_TRY(v4l2_mbus_framefmt, v4l2_subdev_get_try_format, try_fmt)
              | ^~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2102:55: error: passing argument 2 of ‘v4l2_subdev_get_try_format’ makes pointer from integer without a cast [-Werror=int-conversion]
         2102 |                 return v4l2_subdev_get_try_format(fh, pad);
              |                                                       ^~~
              |                                                       |
              |                                                       unsigned int
        In file included from drivers/staging/media/atomisp/include/linux/atomisp_platform.h:26,
                         from drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:22:
        include/media/v4l2-subdev.h:771:49: note: expected ‘struct v4l2_subdev_pad_config *’ but argument is of type ‘unsigned int’
          771 |                  struct v4l2_subdev_pad_config *cfg,                    \
              |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
        include/media/v4l2-subdev.h:778:1: note: in expansion of macro ‘__V4L2_SUBDEV_MK_GET_TRY’
          778 | __V4L2_SUBDEV_MK_GET_TRY(v4l2_mbus_framefmt, v4l2_subdev_get_try_format, try_fmt)
              | ^~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2102:24: error: too few arguments to function ‘v4l2_subdev_get_try_format’
         2102 |                 return v4l2_subdev_get_try_format(fh, pad);
              |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
        In file included from drivers/staging/media/atomisp/include/linux/atomisp_platform.h:26,
                         from drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:22:
        include/media/v4l2-subdev.h:778:46: note: declared here
          778 | __V4L2_SUBDEV_MK_GET_TRY(v4l2_mbus_framefmt, v4l2_subdev_get_try_format, try_fmt)
              |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
        include/media/v4l2-subdev.h:770:9: note: in definition of macro ‘__V4L2_SUBDEV_MK_GET_TRY’
          770 |         fun_name(struct v4l2_subdev *sd,                                \
              |         ^~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c: At top level:
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2353:27: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_pad_config *, struct v4l2_subdev_mbus_code_enum *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_fh *, struct v4l2_subdev_mbus_code_enum *)’ [-Werror=incompatible-pointer-types]
         2353 |         .enum_mbus_code = imx_enum_mbus_code,
              |                           ^~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2353:27: note: (near initialization for ‘imx_pad_ops.enum_mbus_code’)
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2354:28: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_pad_config *, struct v4l2_subdev_frame_size_enum *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_fh *, struct v4l2_subdev_frame_size_enum *)’ [-Werror=incompatible-pointer-types]
         2354 |         .enum_frame_size = imx_enum_frame_size,
              |                            ^~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2354:28: note: (near initialization for ‘imx_pad_ops.enum_frame_size’)
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2355:20: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_pad_config *, struct v4l2_subdev_format *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_fh *, struct v4l2_subdev_format *)’ [-Werror=incompatible-pointer-types]
         2355 |         .get_fmt = imx_get_pad_format,
              |                    ^~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2355:20: note: (near initialization for ‘imx_pad_ops.get_fmt’)
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:2356:20: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_pad_config *, struct v4l2_subdev_format *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_fh *, struct v4l2_subdev_format *)’ [-Werror=incompatible-pointer-types]
         2356 |         .set_fmt = imx_set_pad_format,
              |                    ^~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 5651c258f348cba4b33851cb6814acab8d8a0ade)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 448bba27177c5465e57d103b9eae277dee10e5a4)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>