(port-to-v5.8) atomisp: (mmap locking API) convert mmap_sem call sites
Picked changes for atomisp from commit 89154dd5313f ("mmap locking API:
convert mmap_sem call sites missed by coccinelle").

Also applied the same changes for the parts not exist on the upstream
atomisp.

Fixes:

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c: In function ‘alloc_user_pages’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1096:33: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
         1096 |         down_read(&current->mm->mmap_sem);
              |                                 ^~~~~~~~
              |                                 mmap_base
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1098:31: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
         1098 |         up_read(&current->mm->mmap_sem);
              |                               ^~~~~~~~
              |                               mmap_base
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1119:41: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
         1119 |                 down_read(&current->mm->mmap_sem);
              |                                         ^~~~~~~~
              |                                         mmap_base
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1123:39: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
         1123 |                 up_read(&current->mm->mmap_sem);
              |                                       ^~~~~~~~
              |                                       mmap_base

(cherry picked from commit 31e73655105059e2e25692daab991e180e1cecdc)
[ Conflicts:
	drivers/staging/media/atomisp/pci/atomisp2/hmm/hmm_bo.c
 accepted current]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit acc5f86e67b7503acf6a3d953b12d514b08e5001)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 19a199220fa8c1d36750a67d342af78e20a6a49d)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 36bc316a6b027a187992eef76729ce7b45066030)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>