(port-to-v4.15) atomisp: i2c: Fix function prototypes for module_param_call()
In accordance with commit e4dca7b7aa08 ("treewide: Fix function prototypes
for module_param_call()").

Fixes like:

        In file included from ./include/linux/module.h:18,
                         from drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:23:
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:300:28: error: initialization of ‘int (*)(const char *, const struct kernel_param *)’ from incompatible pointer type ‘int (*)(const char *, struct kernel_param *)’ [-Werror=incompatible-pointer-types]
          300 | module_param_call(dumpotp, ov5693_dump_otp, param_get_uint,
              |                            ^~~~~~~~~~~~~~~
        ./include/linux/moduleparam.h:233:38: note: in definition of macro ‘module_param_call’
          233 |                 { .flags = 0, .set = _set, .get = _get };               \
              |                                      ^~~~
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:300:28: note: (near initialization for ‘__param_ops_dumpotp.set’)
          300 | module_param_call(dumpotp, ov5693_dump_otp, param_get_uint,
              |                            ^~~~~~~~~~~~~~~
        ./include/linux/moduleparam.h:233:38: note: in definition of macro ‘module_param_call’
          233 |                 { .flags = 0, .set = _set, .get = _get };               \
              |                                      ^~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit aa65b9dd4995d570b21632bd9f95a5d33b307664)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit e771f8db2b5f85205d6ab3bafc934acec3b3bf3f)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 804173b12daff029fa22ec34701a19c454510e9e)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>