(TEMP) (revert-for->=v5.12) Revert "sfi: Remove framework for deprecated firmware"
This reverts commit 4590d98f5a4f466d17e5c81d7c9fc796da9a8cee.

There is still a user in aero atomisp:

        In file included from drivers/staging/media/atomisp/platform/atomisp_gmin_platform.c:17:
        drivers/staging/media/atomisp/include/asm/spid.h:36:35: warning: ‘struct sfi_table_header’ declared inside parameter list will not be visible outside of this definition or declaration
           36 | int __init sfi_handle_spid(struct sfi_table_header *table);
              |                                   ^~~~~~~~~~~~~~~~

For now, revert this commit to preserve the original aero atomisp
feature.

Addresses:

        In file included from drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:22:
        drivers/staging/media/atomisp/include/linux/atomisp_platform.h:25:10: fatal error: linux/sfi.h: No such file or directory
           25 | #include <linux/sfi.h>
              |          ^~~~~~~~~~~~~

 Conflicts:
       MAINTAINERS
       arch/x86/include/asm/intel_scu_ipc_legacy.h

arch/x86/include/asm/intel_scu_ipc_legacy.h:
  due to 6517da7aac9d ("x86/platform/intel-mid: Get rid of
  intel_scu_ipc_legacy.h"), removed the file and moved its contents
  into intel-mid.c file. So, dropped the changes to the file
  intel_scu_ipc_legacy.h.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>