(aero-wcove-fix) mfd: intel_soc_pmic: add struct intel_soc_pmic back to linux/mfd/intel_soc_pmic.h
The commit 3610c8f08c93 ("pmic: intel: port whiskey cove driver") moved
struct intel_soc_pmic definition from linux/mfd/intel_soc_pmic.h to
drivers/mfd/intel_soc_pmic_core.h, which breaks at lease intel_pmic_crc
build.

Because the intel_pmic_crc driver is in drivers/pmic and not
drivers/mfd, add the definition back to linux/mfd/intel_soc_pmic.h.
And also add back removed members, at least the regmap member is used
by the intel_pmic_crc driver.

Fixes the following build error:

        drivers/acpi/pmic/intel_pmic_crc.c: In function ‘intel_crc_pmic_opregion_probe’:
        drivers/acpi/pmic/intel_pmic_crc.c:193:60: error: invalid use of undefined type ‘struct intel_soc_pmic’
          193 |                         ACPI_HANDLE(pdev->dev.parent), pmic->regmap,
              |                                                            ^~
        drivers/acpi/pmic/intel_pmic_crc.c:195:1: warning: control reaches end of non-void function [-Wreturn-type]
          195 | }
              | ^

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 38dc30a9b2fe6bb7a766cb0c3c04887dbc81b4f9)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 72aeb26678de935c2ff6f292d40ab6ee9fc2a39c)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>