(port-to-v4.8) atomisp: pci: convert deprecated DEFINE_PCI_DEVICE_TABLE
The DEFINE_PCI_DEVICE_TABLE is removed on commit 7e9321599011 ("treewide:
remove references to the now unnecessary DEFINE_PCI_DEVICE_TABLE").

So, convert it to use "truct pci_device_id".

Ref: 8a793bea2745 ("drivers/scsi/wd719x.c: remove last declaration using DEFINE_PCI_DEVICE_TABLE")

Fixes:

	drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1670:8: error: type defaults to ‘int’ in declaration of ‘DEFINE_PCI_DEVICE_TABLE’ [-Werror=implicit-int]
	 1670 | static DEFINE_PCI_DEVICE_TABLE(atomisp_pci_tbl) = {
	      |        ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit c41a9dd59c88dff8cccfa1817e56b3d628f6d94d)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit fc31bf2b16c0bda268610ae44cd0ad4f34ed2fa9)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit ab43377b21db4fa57d171af0d2b96c8dd3db3f7b)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit e36314f6bc3cd989b343ed3c9da61a6dd0ec345e)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 9d4439d9ecc8677491bbb641f4c2d2dc2333cbd0)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>