(port-to-v5.0) atomisp: i2c: micam/atomisp-ov5693: convert timestamps to ktime_t
Commit 437e78d3fd6d ("timekeeping: remove timespec_add/timespec_del")
on v5.0 removed timespec_add()/timespec_sub(). So, convert it.

Ref:
- 456e7b1804f7 ("media: staging: atomisp: convert timestamps to ktime_t")
- ec8354b98b60 ("staging: imx: use ktime_t for timestamps")

Fixes:

        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c: In function ‘ov5693_q_focus_status’:
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:1256:20: error: implicit declaration of function ‘timespec_sub’; did you mean ‘timespec64_sub’? [-Werror=implicit-function-declaration]
         1256 |         temptime = timespec_sub(temptime, (dev->timestamp_t_focus_abs));
              |                    ^~~~~~~~~~~~
              |                    timespec64_sub

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit d1f6b494c5b827d9fc9f0b2e6cad64e40d0fe701)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 81108ae9aa808bb525659e188a3af9389d8d8962)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>