(port-to-v4.15) atomisp: Convert timers to use timer_setup()
In accordance with commit 513ae785c63c ("timer: Remove setup_*timer()
interface").

While here, remove the unneeded assignment of `asd = &isp->asd[i]`
because it is already done on the `asd` declaration.

Ref:
- mchehab/experimental.git - Mauro's development stuff
  https://git.linuxtv.org/mchehab/experimental.git/commit/?h=yocto_intel_aero_ported_v2&id=2616c5667872506e07ac7b0549ddb049697ff200
  ("media: atomisp: make Yocto's version build with Kernel 5.7")
- 39cbf2aa41b6 ("drm/i915: Convert timers to use timer_setup()")
- 267146d44718 ("drivers/net: smsc: Convert timers to use timer_setup()")

Fixes like:

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c: In function ‘init_atomisp_wdts’:
         1239 |                 setup_timer(&asd->video_out_capture.wdt,
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1239:17: error: implicit declaration of function ‘setup_timer’; did you mean ‘del_timer’? [-Werror=implicit-function-declaration]
              |                 del_timer
              |                 ^~~~~~~~~~~

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c: In function ‘init_atomisp_wdts’:
        ./include/linux/timer.h:114:34: error: passing argument 2 of ‘init_timer_key’ from incompatible pointer type [-Werror=incompatible-pointer-types]
          114 |         init_timer_key((_timer), (_fn), (_flags), NULL, NULL)
              |                                  ^~~~~
              |                                  |
              |                                  void (*)(long unsigned int)
        ./include/linux/timer.h:130:9: note: in expansion of macro ‘__init_timer’
          130 |         __init_timer((timer), (callback), (flags))
              |         ^~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1238:17: note: in expansion of macro ‘timer_setup’
         1238 |                 timer_setup(&asd->video_out_capture.wdt, atomisp_wdt, 0);
              |                 ^~~~~~~~~~~
        ./include/linux/timer.h:80:28: note: expected ‘void (*)(struct timer_list *)’ but argument is of type ‘void (*)(long unsigned int)’
           80 |                     void (*func)(struct timer_list *), unsigned int flags,
              |                     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 26960a2d6df325910053909ba19a59fef5b09750)
[ Conflicts:
	drivers/staging/media/atomisp/pci/atomisp2/atomisp_cmd.c
	drivers/staging/media/atomisp/pci/atomisp2/atomisp_cmd.h
	drivers/staging/media/atomisp/pci/atomisp2/atomisp_v4l2.c]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>