(pick-for-v5.7) media: atomisp: replace VFL_TYPE_GRABBER by VFL_TYPE_VIDEO
This type was renamed in the past by a more meaningul
name. Change it on atomisp too.

Fixes: 238e4a5baa36 ("media: rename VFL_TYPE_GRABBER to _VIDEO")
Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

(cherry picked from commit e58eeb5a7335218498218cde8e96bcf3b7ae4a4a)
[Fixes:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c: In function ‘atomisp_video_register’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:187:51: error: ‘VFL_TYPE_GRABBER’ undeclared (first use in this function); did you mean ‘VFL_TYPE_SUBDEV’?
          187 |         ret = video_register_device(&video->vdev, VFL_TYPE_GRABBER, -1);
              |                                                   ^~~~~~~~~~~~~~~~
              |                                                   VFL_TYPE_SUBDEV
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:187:51: note: each undeclared identifier is reported only once for each function it appears in
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c: In function ‘atomisp_acc_register’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:202:51: error: ‘VFL_TYPE_GRABBER’ undeclared (first use in this function); did you mean ‘VFL_TYPE_SUBDEV’?
          202 |         ret = video_register_device(&video->vdev, VFL_TYPE_GRABBER, -1);
              |                                                   ^~~~~~~~~~~~~~~~
              |                                                   VFL_TYPE_SUBDEV
]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>

(cherry picked from commit 476659d5328fe6b61802d8044121740987304ae2)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 6cb5007f0655358e374578ff6d98244ac5b247e4)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 297855e1df31b0e67737cde404d28994541299ba)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>