(port-to-v4.5) atomisp: Rename entities types to functions
MEDIA_ENT_T_V4L2_SUBDEV -> MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN
MEDIA_ENT_T_DEVNODE -> MEDIA_ENT_F_OLD_BASE

in accordance with commit 4ca72efaeffd ("[media] uapi/media.h: Rename
entities types to functions") added on v4.5-rc1.

Ref:
- mchehab/experimental.git - Mauro's development stuff
  https://git.linuxtv.org/mchehab/experimental.git/commit/?h=yocto_intel_aero_ported_v2&id=2616c5667872506e07ac7b0549ddb049697ff200
  ("media: atomisp: make Yocto's version build with Kernel 5.7")

Fixes errors like the following:

    drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_tpg.c: In function ‘atomisp_tpg_init’:
    drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_tpg.c:229:24: error: ‘MEDIA_ENT_T_V4L2_SUBDEV’ undeclared (first use in this function); did you mean ‘MEDIA_INTF_T_V4L_SUBDEV’?
      229 |         me->function = MEDIA_ENT_T_V4L2_SUBDEV;
          |                        ^~~~~~~~~~~~~~~~~~~~~~~
          |                        MEDIA_INTF_T_V4L_SUBDEV

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit f8a7256896b4508bd93172ec269c2cceae74c6fd)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit b2af8629a1089a29e68a98a89a7465fdc7e377bb)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 95621820cb8592c9dcd644532cdcee3f965a7228)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit ab9cdf65bd5d484ee6868fb82ddd437bc3a6f2ff)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 47e78d25eb4aefdb0c04b8fe7a7b4e61826fef6f)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit af2a750693a5bb037f3f33db22967ffa811b167c)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>