(aero44) atomisp: imx: replace "enum v4l2_mbus_pixelcode" with u32
Replace it with u32 as done so in the intel-aero sensor drivers.

        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:914:1: error: return type is an incomplete type
          914 | imx_translate_bayer_order(enum atomisp_bayer_order code)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        In file included from ./include/uapi/linux/v4l2-mediabus.h:14,
                         from ./include/uapi/linux/v4l2-subdev.h:29,
                         from include/media/v4l2-subdev.h:25,
                         from drivers/staging/media/atomisp/include/linux/atomisp_platform.h:26,
                         from drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:22:
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c: In function ‘imx_translate_bayer_order’:
        ./include/uapi/linux/media-bus-format.h:120:49: error: ‘return’ with a value, in function returning void [-Werror=return-type]
          120 | #define MEDIA_BUS_FMT_SRGGB10_1X10              0x300f
              |                                                 ^~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:918:24: note: in expansion of macro ‘MEDIA_BUS_FMT_SRGGB10_1X10’
          918 |                 return MEDIA_BUS_FMT_SRGGB10_1X10;
              |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:914:1: note: declared here
          914 | imx_translate_bayer_order(enum atomisp_bayer_order code)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        In file included from ./include/uapi/linux/v4l2-mediabus.h:14,
                         from ./include/uapi/linux/v4l2-subdev.h:29,
                         from include/media/v4l2-subdev.h:25,
                         from drivers/staging/media/atomisp/include/linux/atomisp_platform.h:26,
                         from drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:22:
        ./include/uapi/linux/media-bus-format.h:119:49: error: ‘return’ with a value, in function returning void [-Werror=return-type]
          119 | #define MEDIA_BUS_FMT_SGRBG10_1X10              0x300a
              |                                                 ^~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:920:24: note: in expansion of macro ‘MEDIA_BUS_FMT_SGRBG10_1X10’
          920 |                 return MEDIA_BUS_FMT_SGRBG10_1X10;
              |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:914:1: note: declared here
          914 | imx_translate_bayer_order(enum atomisp_bayer_order code)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        In file included from ./include/uapi/linux/v4l2-mediabus.h:14,
                         from ./include/uapi/linux/v4l2-subdev.h:29,
                         from include/media/v4l2-subdev.h:25,
                         from drivers/staging/media/atomisp/include/linux/atomisp_platform.h:26,
                         from drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:22:
        ./include/uapi/linux/media-bus-format.h:117:49: error: ‘return’ with a value, in function returning void [-Werror=return-type]
          117 | #define MEDIA_BUS_FMT_SBGGR10_1X10              0x3007
              |                                                 ^~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:922:24: note: in expansion of macro ‘MEDIA_BUS_FMT_SBGGR10_1X10’
          922 |                 return MEDIA_BUS_FMT_SBGGR10_1X10;
              |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:914:1: note: declared here
          914 | imx_translate_bayer_order(enum atomisp_bayer_order code)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        In file included from ./include/uapi/linux/v4l2-mediabus.h:14,
                         from ./include/uapi/linux/v4l2-subdev.h:29,
                         from include/media/v4l2-subdev.h:25,
                         from drivers/staging/media/atomisp/include/linux/atomisp_platform.h:26,
                         from drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:22:
        ./include/uapi/linux/media-bus-format.h:118:49: error: ‘return’ with a value, in function returning void [-Werror=return-type]
          118 | #define MEDIA_BUS_FMT_SGBRG10_1X10              0x300e
              |                                                 ^~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:924:24: note: in expansion of macro ‘MEDIA_BUS_FMT_SGBRG10_1X10’
          924 |                 return MEDIA_BUS_FMT_SGBRG10_1X10;
              |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:914:1: note: declared here
          914 | imx_translate_bayer_order(enum atomisp_bayer_order code)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:926:16: error: ‘return’ with a value, in function returning void [-Werror=return-type]
          926 |         return 0;
              |                ^
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:914:1: note: declared here
          914 | imx_translate_bayer_order(enum atomisp_bayer_order code)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c: In function ‘imx_v_flip’:
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:962:34: error: void value not ignored as it ought to be
          962 |                 dev->format.code = imx_translate_bayer_order(
              |                                  ^
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c: In function ‘imx_h_flip’:
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:1000:34: error: void value not ignored as it ought to be
         1000 |                 dev->format.code = imx_translate_bayer_order(
              |                                  ^
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c: In function ‘imx_s_mbus_fmt’:
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:1724:26: error: void value not ignored as it ought to be
         1724 |         dev->format.code = imx_translate_bayer_order(
              |                          ^
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c: In function ‘imx_enum_mbus_fmt’:
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:1965:15: error: invalid use of undefined type ‘enum v4l2_mbus_pixelcode’
         1965 |         *code = dev->format.code;
              |               ^

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 308489a184d309c478fa0f6ffa9f869cadddadfb)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>