clk: clk-tps68470: (port-to-v4.6-rc1) remove CLK_IS_ROOT
In accordance with commit 1edfc1e700c0 ("clk: pwm: Remove CLK_IS_ROOT")
added on v4.6-rc1

Fixes the following compile error:

    drivers/clk/clk-tps68470.c:210:11: error: ‘CLK_IS_ROOT’ undeclared here (not in a function); did you mean ‘IS_ROOT’?
      210 |  .flags = CLK_IS_ROOT,
          |           ^~~~~~~~~~~
          |           IS_ROOT

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>