(WIP) atomisp: pci: revert ("make all file names unique at atomisp driver") to fix build
This commit reverts b82cd6b7f58 ("media: atomisp: make all file names
unique at atomisp driver").

TODO:
  Why this commit breaks build?

Used the following command:

	git rm drivers/staging/media/atomisp/pci/input_system_global.h
	git rm drivers/staging/media/atomisp/pci/input_system_local.h
	git rm drivers/staging/media/atomisp/pci/input_system_private.h
	git rm drivers/staging/media/atomisp/pci/input_system_public.h

	cd drivers/staging/media/atomisp/pci/
	mkdir -p hive_isp_css_common/host/
	git mv isp2400_input_system_local.h hive_isp_css_common/host/input_system_local.h
	git mv isp2400_input_system_private.h hive_isp_css_common/host/input_system_private.h
	git mv isp2400_input_system_public.h hive_isp_css_include/host/input_system_public.h
	git mv isp2400_system_global.h hive_isp_css_common/system_global.h
	git mv isp2400_system_local.h hive_isp_css_common/host/system_local.h
	git mv isp2401_input_system_global.h css_2401_csi2p_system/input_system_global.h
	git mv isp2401_input_system_local.h css_2401_csi2p_system/host/input_system_local.h
	git mv isp2401_input_system_private.h css_2401_csi2p_system/host/input_system_private.h
	git mv isp2401_system_global.h css_2401_csi2p_system/system_global.h
	git mv isp2401_system_local.h css_2401_csi2p_system/host/system_local.h

	cd -
	git rm drivers/staging/media/atomisp/pci/system_global.h
	git rm drivers/staging/media/atomisp/pci/system_local.h

	cd drivers/staging/media/atomisp/pci/
	git mv isp2400_input_system_global.h hive_isp_css_common/input_system_global.h

Fixes:

	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/ibuf_ctrl.c:18:29: error: ‘N_IBUF_CTRL_ID’ undeclared here (not in a function); did you mean ‘N_TIMED_CTRL_ID’?
	   18 | const u32 N_IBUF_CTRL_PROCS[N_IBUF_CTRL_ID] = {
	      |                             ^~~~~~~~~~~~~~
	      |                             N_TIMED_CTRL_ID
	make[1]: *** [scripts/Makefile.build:277: drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/ibuf_ctrl.o] Error 1
	make[1]: *** Waiting for unfinished jobs....
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/csi_rx.c:17:38: error: ‘N_CSI_RX_BACKEND_ID’ undeclared here (not in a function)
	   17 | const u32 N_SHORT_PACKET_LUT_ENTRIES[N_CSI_RX_BACKEND_ID] = {
	      |                                      ^~~~~~~~~~~~~~~~~~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/csi_rx.c:29:35: error: ‘N_CSI_RX_FRONTEND_ID’ undeclared here (not in a function)
	   29 | const u32 N_CSI_RX_FE_CTRL_DLANES[N_CSI_RX_FRONTEND_ID] = {
	      |                                   ^~~~~~~~~~~~~~~~~~~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/csi_rx.c:30:9: error: ‘N_CSI_RX_DLANE_ID’ undeclared here (not in a function)
	   30 |         N_CSI_RX_DLANE_ID,      /* 4 dlanes for CSI_RX_FR0NTEND0_ID */
	      |         ^~~~~~~~~~~~~~~~~
	make[1]: *** [scripts/Makefile.build:277: drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/csi_rx.o] Error 1
	In file included from ./drivers/staging/media/atomisp//pci/css_2401_csi2p_system/host/isys_dma_local.h:18,
			 from ./drivers/staging/media/atomisp//pci/hive_isp_css_include/isys_dma.h:34,
			 from drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.c:15:
	./drivers/staging/media/atomisp//pci/css_2401_csi2p_system/isys_dma_global.h:77:9: error: unknown type name ‘isys2401_dma_channel’
	   77 |         isys2401_dma_channel    channel;
	      |         ^~~~~~~~~~~~~~~~~~~~
	./drivers/staging/media/atomisp//pci/css_2401_csi2p_system/isys_dma_global.h:86:14: error: unknown type name ‘isys2401_dma_channel’
	   86 | extern const isys2401_dma_channel
	      |              ^~~~~~~~~~~~~~~~~~~~
	./drivers/staging/media/atomisp//pci/css_2401_csi2p_system/isys_dma_global.h:87:30: error: ‘N_ISYS2401_DMA_ID’ undeclared here (not in a function)
	   87 | N_ISYS2401_DMA_CHANNEL_PROCS[N_ISYS2401_DMA_ID];
	      |                              ^~~~~~~~~~~~~~~~~
	In file included from drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.c:23:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma_private.h:26:11: error: unknown type name ‘isys2401_dma_ID_t’
	   26 |     const isys2401_dma_ID_t     dma_id,
	      |           ^~~~~~~~~~~~~~~~~
	In file included from drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.c:16:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma_private.h: In function ‘isys2401_dma_reg_store’:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma_private.h:33:16: error: ‘ISYS2401_DMA_BASE’ undeclared (first use in this function)
	   33 |         assert(ISYS2401_DMA_BASE[dma_id] != (hrt_address) - 1);
	      |                ^~~~~~~~~~~~~~~~~
	./drivers/staging/media/atomisp//pci/hive_isp_css_include/assert_support.h:55:23: note: in definition of macro ‘assert’
	   55 |                 if (!(cnd)) \
	      |                       ^~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma_private.h:33:16: note: each undeclared identifier is reported only once for each function it appears in
	   33 |         assert(ISYS2401_DMA_BASE[dma_id] != (hrt_address) - 1);
	      |                ^~~~~~~~~~~~~~~~~
	./drivers/staging/media/atomisp//pci/hive_isp_css_include/assert_support.h:55:23: note: in definition of macro ‘assert’
	   55 |                 if (!(cnd)) \
	      |                       ^~~
	In file included from drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.c:23:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma_private.h: At top level:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma_private.h:43:11: error: unknown type name ‘isys2401_dma_ID_t’
	   43 |     const isys2401_dma_ID_t     dma_id,
	      |           ^~~~~~~~~~~~~~~~~
	In file included from drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.c:16:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma_private.h: In function ‘isys2401_dma_reg_load’:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma_private.h:50:16: error: ‘ISYS2401_DMA_BASE’ undeclared (first use in this function)
	   50 |         assert(ISYS2401_DMA_BASE[dma_id] != (hrt_address) - 1);
	      |                ^~~~~~~~~~~~~~~~~
	./drivers/staging/media/atomisp//pci/hive_isp_css_include/assert_support.h:55:23: note: in definition of macro ‘assert’
	   55 |                 if (!(cnd)) \
	      |                       ^~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.c: At top level:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.c:26:7: error: unknown type name ‘isys2401_dma_channel’
	   26 | const isys2401_dma_channel N_ISYS2401_DMA_CHANNEL_PROCS[N_ISYS2401_DMA_ID] = {
	      |       ^~~~~~~~~~~~~~~~~~~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.c:27:9: error: ‘N_ISYS2401_DMA_CHANNEL’ undeclared here (not in a function); did you mean ‘N_ISYS2401_DMA_CHANNEL_PROCS’?
	   27 |         N_ISYS2401_DMA_CHANNEL
	      |         ^~~~~~~~~~~~~~~~~~~~~~
	      |         N_ISYS2401_DMA_CHANNEL_PROCS
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.c:31:11: error: unknown type name ‘isys2401_dma_ID_t’
	   31 |     const isys2401_dma_ID_t     dma_id,
	      |           ^~~~~~~~~~~~~~~~~
	make[1]: *** [scripts/Makefile.build:277: drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_dma.o] Error 1
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:30:29: error: expected ‘;’ before ‘void’
	   30 | STORAGE_CLASS_ISYS2401_IRQ_C void isys_irqc_status_enable(
	      |                             ^~~~~
	      |                             ;
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:31:11: error: unknown type name ‘isys_irq_ID_t’
	   31 |     const isys_irq_ID_t isys_irqc_id)
	      |           ^~~~~~~~~~~~~
	In file included from drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:17:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c: In function ‘isys_irqc_status_enable’:
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:33:31: error: ‘N_ISYS_IRQ_ID’ undeclared (first use in this function); did you mean ‘N_IRQ_ID’?
	   33 |         assert(isys_irqc_id < N_ISYS_IRQ_ID);
	      |                               ^~~~~~~~~~~~~
	./drivers/staging/media/atomisp//pci/hive_isp_css_include/assert_support.h:55:23: note: in definition of macro ‘assert’
	   55 |                 if (!(cnd)) \
	      |                       ^~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:33:31: note: each undeclared identifier is reported only once for each function it appears in
	   33 |         assert(isys_irqc_id < N_ISYS_IRQ_ID);
	      |                               ^~~~~~~~~~~~~
	./drivers/staging/media/atomisp//pci/hive_isp_css_include/assert_support.h:55:23: note: in definition of macro ‘assert’
	   55 |                 if (!(cnd)) \
	      |                       ^~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:37:9: error: implicit declaration of function ‘isys_irqc_reg_store’ [-Werror=implicit-function-declaration]
	   37 |         isys_irqc_reg_store(isys_irqc_id, ISYS_IRQ_MASK_REG_IDX,
	      |         ^~~~~~~~~~~~~~~~~~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:37:43: error: ‘ISYS_IRQ_MASK_REG_IDX’ undeclared (first use in this function)
	   37 |         isys_irqc_reg_store(isys_irqc_id, ISYS_IRQ_MASK_REG_IDX,
	      |                                           ^~~~~~~~~~~~~~~~~~~~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:38:29: error: ‘ISYS_IRQ_MASK_REG_VALUE’ undeclared (first use in this function)
	   38 |                             ISYS_IRQ_MASK_REG_VALUE);
	      |                             ^~~~~~~~~~~~~~~~~~~~~~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:39:43: error: ‘ISYS_IRQ_CLEAR_REG_IDX’ undeclared (first use in this function); did you mean ‘ISP_IRQ_CLEAR_REG’?
	   39 |         isys_irqc_reg_store(isys_irqc_id, ISYS_IRQ_CLEAR_REG_IDX,
	      |                                           ^~~~~~~~~~~~~~~~~~~~~~
	      |                                           ISP_IRQ_CLEAR_REG
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:40:29: error: ‘ISYS_IRQ_CLEAR_REG_VALUE’ undeclared (first use in this function); did you mean ‘ISP_IRQ_CLEAR_REG’?
	   40 |                             ISYS_IRQ_CLEAR_REG_VALUE);
	      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
	      |                             ISP_IRQ_CLEAR_REG
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:41:43: error: ‘ISYS_IRQ_ENABLE_REG_IDX’ undeclared (first use in this function)
	   41 |         isys_irqc_reg_store(isys_irqc_id, ISYS_IRQ_ENABLE_REG_IDX,
	      |                                           ^~~~~~~~~~~~~~~~~~~~~~~
	drivers/staging/media/atomisp/pci/css_2401_csi2p_system/host/isys_irq.c:42:29: error: ‘ISYS_IRQ_ENABLE_REG_VALUE’ undeclared (first use in this function)
	   42 |                             ISYS_IRQ_ENABLE_REG_VALUE);
	      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>