NOTE: wcove "undefined reference"
To build this kernel tree, currently, need to disable some configs like
the following:

        CONFIG_INPUT_MPU3050=n
        CONFIG_SENSORS_EMC1403=n
        CONFIG_SENSORS_LIS3LV02D=n
        CONFIG_SENSORS_LIS3_SPI=n
        CONFIG_SENSORS_LIS3_I2C=n
        CONFIG_HP_ACCEL=n
        CONFIG_INTEL_CHT_PHY=n
        CONFIG_INTEL_SOC_PMIC_CCSM=n

The config `CONFIG_INTEL_SOC_PMIC_CCSM` is my HACK, to avoid disabling
`CONFIG_INTEL_SOC_PMIC`.

Without disabling those configs, we get the following errors:

          LD      init/built-in.o
        ld: arch/x86/built-in.o: in function `mpu3050_platform_data':
        platform_mpu3050.c:(.text+0x721e5): undefined reference to `get_gpio_by_name'
        ld: arch/x86/built-in.o: in function `emc1403_platform_data':
        platform_emc1403.c:(.init.text+0x20ac7): undefined reference to `get_gpio_by_name'
        ld: platform_emc1403.c:(.init.text+0x20ad5): undefined reference to `get_gpio_by_name'
        ld: arch/x86/built-in.o: in function `lis331dl_platform_data':
        platform_lis331.c:(.init.text+0x20b1b): undefined reference to `get_gpio_by_name'
        ld: platform_lis331.c:(.init.text+0x20b29): undefined reference to `get_gpio_by_name'
        ld: drivers/built-in.o: in function `fsm_show':
        phy-intel-cht.c:(.text+0x142f36): undefined reference to `usb_otg_state_string'
        ld: drivers/built-in.o: in function `cht_handle_extcon_otg_event':
        phy-intel-cht.c:(.text+0x14315c): undefined reference to `extcon_get_cable_state'
        ld: drivers/built-in.o: in function `cht_otg_fsm_work':
        phy-intel-cht.c:(.text+0x14321d): undefined reference to `otg_statemachine'
        ld: drivers/built-in.o: in function `cht_otg_set_peripheral':
        phy-intel-cht.c:(.text+0x14327d): undefined reference to `otg_statemachine'
        ld: drivers/built-in.o: in function `cht_otg_set_host':
        phy-intel-cht.c:(.text+0x1432e9): undefined reference to `extcon_get_cable_state'
        ld: phy-intel-cht.c:(.text+0x143318): undefined reference to `otg_statemachine'
        ld: drivers/built-in.o: in function `cht_otg_set_power':
        phy-intel-cht.c:(.text+0x1433a1): undefined reference to `usb_otg_state_string'
        ld: drivers/built-in.o: in function `cht_otg_probe':
        phy-intel-cht.c:(.text+0x1435d1): undefined reference to `extcon_register_interest'
        ld: phy-intel-cht.c:(.text+0x143642): undefined reference to `otg_statemachine'
        ld: phy-intel-cht.c:(.text+0x143734): undefined reference to `extcon_unregister_interest'
        ld: drivers/built-in.o: in function `cht_otg_start_gadget':
        phy-intel-cht.c:(.text+0x143865): undefined reference to `usb_hcd_is_primary_hcd'
        ld: phy-intel-cht.c:(.text+0x143893): undefined reference to `xhci_intel_phy_vbus_valid'
        ld: drivers/built-in.o: in function `cht_otg_start_host':
        phy-intel-cht.c:(.text+0x14397d): undefined reference to `usb_hcd_is_primary_hcd'
        ld: phy-intel-cht.c:(.text+0x1439ab): undefined reference to `xhci_intel_phy_mux_switch'
        ld: drivers/built-in.o: in function `cht_otg_remove':
        phy-intel-cht.c:(.text+0x143a5b): undefined reference to `extcon_unregister_interest'
        ld: drivers/built-in.o: in function `pmic_ccsm_usb_host_nb':
        intel_pmic_ccsm.c:(.text+0x1584b4): undefined reference to `extcon_get_cable_state'
        ld: drivers/built-in.o: in function `pmic_chrgr_probe':
        intel_pmic_ccsm.c:(.text+0x158fc2): undefined reference to `extcon_register_interest'
        ld: intel_pmic_ccsm.c:(.text+0x159130): undefined reference to `extcon_get_extcon_dev'
        ld: intel_pmic_ccsm.c:(.text+0x159148): undefined reference to `extcon_get_cable_state'
        ld: drivers/built-in.o: in function `pmic_event_worker':
        intel_pmic_ccsm.c:(.text+0x159e20): undefined reference to `iio_channel_get'
        ld: intel_pmic_ccsm.c:(.text+0x159e45): undefined reference to `iio_read_channel_raw'
        ld: intel_pmic_ccsm.c:(.text+0x159e7b): undefined reference to `iio_channel_release'
        ld: intel_pmic_ccsm.c:(.text+0x15a004): undefined reference to `iio_channel_release'
        make: *** [Makefile:992: vmlinux] Error 1

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>