(WIP) atomisp: pci: re-add HAS_NO_INPUT_FORMATTER/USE_INPUT_SYSTEM_VERSION_2 where really needed in ia_css_debug.c
WIP:
  Why this is broken here but not broken on the upstream atomisp?
  Maybe due to 1d13356c684f ("(WIP) atomisp: pci: revert ("make all file
  names unique at atomisp driver") to fix build")

This fixes the following build error for ISP2401:

        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1657:44: error: unknown type name ‘mipi_port_state_t’; did you mean ‘dma_port_state_t’?
         1657 | static void debug_print_rx_mipi_port_state(mipi_port_state_t *state)
              |                                            ^~~~~~~~~~~~~~~~~
              |                                            dma_port_state_t
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1732:42: error: unknown type name ‘rx_channel_state_t’; did you mean ‘dma_channel_state_t’?
         1732 | static void debug_print_rx_channel_state(rx_channel_state_t *state)
              |                                          ^~~~~~~~~~~~~~~~~~
              |                                          dma_channel_state_t
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1756:34: error: unknown type name ‘receiver_state_t’
         1756 | static void debug_print_rx_state(receiver_state_t *state)
              |                                  ^~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c: In function ‘ia_css_debug_dump_rx_state’:
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1854:9: error: unknown type name ‘receiver_state_t’
         1854 |         receiver_state_t state;
              |         ^~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1856:9: error: implicit declaration of function ‘receiver_get_state’ [-Werror=implicit-function-declaration]
         1856 |         receiver_get_state(RX0_ID, &state);
              |         ^~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1857:9: error: implicit declaration of function ‘debug_print_rx_state’; did you mean ‘debug_print_if_state’? [-Werror=implicit-function-declaration]
         1857 |         debug_print_rx_state(&state);
              |         ^~~~~~~~~~~~~~~~~~~~
              |         debug_print_if_state
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c: At top level:
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1873:49: error: unknown type name ‘capture_unit_state_t’
         1873 | static void debug_print_isys_capture_unit_state(capture_unit_state_t *state)
              |                                                 ^~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1920:5: error: unknown type name ‘acquisition_unit_state_t’
         1920 |     acquisition_unit_state_t *state)
              |     ^~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1960:46: error: unknown type name ‘ctrl_unit_state_t’
         1960 | static void debug_print_isys_ctrl_unit_state(ctrl_unit_state_t *state)
              |                                              ^~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c: In function ‘debug_print_isys_state’:
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2046:56: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘str_multicastA_sel’
         2046 |                             "str_multiCastA_sel", state->str_multicastA_sel);
              |                                                        ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2049:56: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘str_multicastB_sel’
         2049 |                             "str_multicastB_sel", state->str_multicastB_sel);
              |                                                        ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2052:56: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘str_multicastC_sel’
         2052 |                             "str_multicastC_sel", state->str_multicastC_sel);
              |                                                        ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2055:49: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘str_mux_sel’
         2055 |                             "str_mux_sel", state->str_mux_sel);
              |                                                 ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2058:52: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘str_mon_status’
         2058 |                             "str_mon_status", state->str_mon_status);
              |                                                    ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2061:54: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘str_mon_irq_cond’
         2061 |                             "str_mon_irq_cond", state->str_mon_irq_cond);
              |                                                      ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2064:52: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘str_mon_irq_en’
         2064 |                             "str_mon_irq_en", state->str_mon_irq_en);
              |                                                    ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2067:47: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘isys_srst’
         2067 |                             "isys_srst", state->isys_srst);
              |                                               ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2070:55: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘isys_slv_reg_srst’
         2070 |                             "isys_slv_reg_srst", state->isys_slv_reg_srst);
              |                                                       ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2073:57: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘str_deint_portA_cnt’
         2073 |                             "str_deint_portA_cnt", state->str_deint_portA_cnt);
              |                                                         ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2076:57: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘str_deint_portB_cnt’
         2076 |                             "str_deint_portB_cnd", state->str_deint_portB_cnt);
              |                                                         ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2081:17: error: unknown type name ‘capture_unit_state_t’
         2081 |                 capture_unit_state_t *capture_unit_state;
              |                 ^~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2085:44: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘capture_unit’
         2085 |                 capture_unit_state = &state->capture_unit[i];
              |                                            ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2086:17: error: implicit declaration of function ‘debug_print_isys_capture_unit_state’ [-Werror=implicit-function-declaration]
         2086 |                 debug_print_isys_capture_unit_state(capture_unit_state);
              |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2092:17: error: unknown type name ‘acquisition_unit_state_t’
         2092 |                 acquisition_unit_state_t *acquisition_unit_state;
              |                 ^~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2096:48: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘acquisition_unit’
         2096 |                 acquisition_unit_state = &state->acquisition_unit[i];
              |                                                ^~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2097:17: error: implicit declaration of function ‘debug_print_isys_acquisition_unit_state’ [-Werror=implicit-function-declaration]
         2097 |                 debug_print_isys_acquisition_unit_state(acquisition_unit_state);
              |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2105:17: error: implicit declaration of function ‘debug_print_isys_ctrl_unit_state’; did you mean ‘debug_print_isys_state’? [-Werror=implicit-function-declaration]
         2105 |                 debug_print_isys_ctrl_unit_state(&state->ctrl_unit_state[i]);
              |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              |                 debug_print_isys_state
        drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:2105:56: error: ‘input_system_state_t’ {aka ‘struct input_system_state_s’} has no member named ‘ctrl_unit_state’
         2105 |                 debug_print_isys_ctrl_unit_state(&state->ctrl_unit_state[i]);
              |                                                        ^~

Reference: bd674b5a413c ("media: atomisp: cleanup ifdefs from ia_css_debug.c")
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>