(fix-aero) atomisp: revert changes for intel-mid/{Makefile,device_libs/Makefile} done by atomisp patch
The atomisp patch from intel-aero 5ec3de498560 ("temp: atomisp support")
somehow modifies intel-mid/Makefile and intel-mid/device_libs/Makefile,
which breaks kernel build on link stage like the following:

        ld: arch/x86/built-in.o: in function `pb_keys_init':
        platform_gpio_keys.c:(.init.text+0x20864): undefined reference to `get_gpio_by_name'
        make: *** [Makefile:992: vmlinux] Error 1

Fix it by reverting the changes.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 51a686f62498e005b0716eef6fd8305e48680fa4)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>