(for->=-v5.10) atomisp: add missing lm3554.h header file from upstream v5.14-rc6
Fixes:

        drivers/staging/media/atomisp/i2c/atomisp-lm3554.c:25:10: fatal error: ../include/media/lm3554.h: No such file or directory
           25 | #include "../include/media/lm3554.h"
              |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>