regulator: tps68470-regulator: (port-to-v5.8-rc1) use linear_ranges helper
In accordance with commit 60ab7f4153b6 ("regulator: use linear_ranges
helper") added on v5.8-rc1

Fixes the following compile error:

    drivers/regulator/tps68470-regulator.c:61:44: error: array type has incomplete element type ‘struct regulator_linear_range’
       61 | static const struct regulator_linear_range tps68470_ldo_ranges[] = {
          |                                            ^~~~~~~~~~~~~~~~~~~
    drivers/regulator/tps68470-regulator.c:65:44: error: array type has incomplete element type ‘struct regulator_linear_range’
       65 | static const struct regulator_linear_range tps68470_core_ranges[] = {
          |                                            ^~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>