atomisp: micam: fix Kconfig (upstream atomisp-ov5693 vs micam/atomisp-ov5693)
Fixes:

          GEN     .version
        error: the following would cause module name conflict:
          drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.ko
          drivers/staging/media/atomisp/i2c/ov5693/atomisp-ov5693.ko
        make: *** [Makefile:1417: modules_check] Error 1

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 22b5d9f4906cea94835fa2b26fa5ab0a7e5268e5)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>