(port-to-v5.0) atomisp: Remove 'type' argument from access_ok() function
In accordance with commit 96d4f267e40f ("Remove 'type' argument from
access_ok() function").

Ref: 60e5c189453f ("media: atomisp: fix usage of access_ok() kAPI")

Fixes like:

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_ioctl32.c: In function ‘get_atomisp_histogram32’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_ioctl32.c:35:75: error: macro "access_ok" passed 3 arguments, but takes just 2
           35 |         if (!access_ok(VERIFY_READ, up, sizeof(struct atomisp_histogram32)) ||
              |                                                                           ^
        In file included from ./include/linux/uaccess.h:11,
                         from ./include/linux/crypto.h:21,
                         from ./include/crypto/hash.h:11,
                         from ./include/linux/uio.h:10,
                         from ./include/linux/socket.h:8,
                         from ./include/linux/compat.h:15,
                         from drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_ioctl32.c:22:
        ./arch/x86/include/asm/uaccess.h:93: note: macro "access_ok" defined here
           93 | #define access_ok(addr, size)                                   \
              |
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_ioctl32.c:35:14: error: ‘access_ok’ undeclared (first use in this function)
           35 |         if (!access_ok(VERIFY_READ, up, sizeof(struct atomisp_histogram32)) ||
              |              ^~~~~~~~~
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_ioctl32.c:35:14: note: each undeclared identifier is reported only once for each function it appears in
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_ioctl32.c: In function ‘put_atomisp_histogram32’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_compat_ioctl32.c:49:76: error: macro "access_ok" passed 3 arguments, but takes just 2
           49 |         if (!access_ok(VERIFY_WRITE, up, sizeof(struct atomisp_histogram32)) ||
              |                                                                            ^

(cherry picked from commit 11092a27f6e70a936f851d701d42275eeb8e2337)
[ Conflicts:
	drivers/staging/media/atomisp/pci/atomisp2/atomisp_compat_ioctl32.c]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit d2ce8d6853fd95d908b9e4283943cf181367919d)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>