(TEMP) (revert-for->=-v4.14) Revert "media: media-device: remove driver_version"
This reverts commit 2bd8682375f3a79e463d8840794d2872b02d755b.

Still used on atomisp. Convert to drop driver_version later.

Address like:

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c: In function ‘atomisp_subdev_init’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c:1663:45: error: ‘struct media_device’ has no member named ‘driver_version’
         1663 |         isp->num_of_streams = isp->media_dev.driver_version >=
              |                                             ^
        make[3]: *** [scripts/Makefile.build:329: drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.o] Error 1
        make[3]: *** Waiting for unfinished jobs....
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c: In function ‘atomisp_load_firmware’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1184:39: error: ‘struct media_device’ has no member named ‘driver_version’
         1184 |                         isp->media_dev.driver_version,
              |                                       ^
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c: In function ‘atomisp_pci_probe’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1329:23: error: ‘struct media_device’ has no member named ‘driver_version’
         1329 |         isp->media_dev.driver_version = ATOMISP_CSS_VERSION_21;
              |                       ^

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>