(port-to-v3.19) atomisp: imx: use MEDIA_BUS_FMT_* instead
In accordance with commit f5fe58fd76a0 ("[media] i2c: Make use of
media_bus_format enum") added on v3.19-rc1.

Fixes:

        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c: In function ‘imx_translate_bayer_order’:
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:918:24: error: ‘V4L2_MBUS_FMT_SRGGB10_1X10’ undeclared (first use in this function); did you mean ‘MEDIA_BUS_FMT_SRGGB10_1X10’?
          918 |                 return V4L2_MBUS_FMT_SRGGB10_1X10;
              |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
              |                        MEDIA_BUS_FMT_SRGGB10_1X10
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:918:24: note: each undeclared identifier is reported only once for each function it appears in
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:918:24: error: ‘return’ with a value, in function returning void [-Werror=return-type]
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:914:1: note: declared here
          914 | imx_translate_bayer_order(enum atomisp_bayer_order code)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:920:24: error: ‘V4L2_MBUS_FMT_SGRBG10_1X10’ undeclared (first use in this function); did you mean ‘MEDIA_BUS_FMT_SGRBG10_1X10’?
          920 |                 return V4L2_MBUS_FMT_SGRBG10_1X10;
              |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
              |                        MEDIA_BUS_FMT_SGRBG10_1X10
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:920:24: error: ‘return’ with a value, in function returning void [-Werror=return-type]
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:914:1: note: declared here
          914 | imx_translate_bayer_order(enum atomisp_bayer_order code)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:922:24: error: ‘V4L2_MBUS_FMT_SBGGR10_1X10’ undeclared (first use in this function); did you mean ‘MEDIA_BUS_FMT_SBGGR10_1X10’?
          922 |                 return V4L2_MBUS_FMT_SBGGR10_1X10;
              |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
              |                        MEDIA_BUS_FMT_SBGGR10_1X10
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:922:24: error: ‘return’ with a value, in function returning void [-Werror=return-type]
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:914:1: note: declared here
          914 | imx_translate_bayer_order(enum atomisp_bayer_order code)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/imx/atomisp-imx.c:924:24: error: ‘V4L2_MBUS_FMT_SGBRG10_1X10’ undeclared (first use in this function); did you mean ‘MEDIA_BUS_FMT_SGBRG10_1X10’?
          924 |                 return V4L2_MBUS_FMT_SGBRG10_1X10;
              |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
              |                        MEDIA_BUS_FMT_SGBRG10_1X10

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 7637eccd7df23b609d39f0634c29df3bad84a0f9)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>