(port-to-v5.7) media: atomisp: use cpu_latency_qos_*() instead of pm_qos_update*()
Those functions got renamed. Update them on atomisp driver.

Fixes: 67b06ba01857 ("PM: QoS: Drop PM_QOS_CPU_DMA_LATENCY and rename related functions")
Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

(cherry picked from commit 8d564cd28cfcbea636b44a96a1edfe0e3395ef60)
[ Conflicts:
	drivers/staging/media/atomisp/pci/atomisp_driver/atomisp_v4l2.c
 resolved manually]
[Fixes like:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c: In function ‘atomisp_runtime_suspend’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:535:9: error: implicit declaration of function ‘pm_qos_update_request’; did you mean ‘freq_qos_update_request’? [-Werror=implicit-function-declaration]
          535 |         pm_qos_update_request(&isp->pm_qos, PM_QOS_DEFAULT_VALUE);
              |         ^~~~~~~~~~~~~~~~~~~~~
              |         freq_qos_update_request
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1457:9: error: implicit declaration of function ‘pm_qos_add_request’; did you mean ‘freq_qos_add_request’? [-Werror=implicit-function-declaration]
         1457 |         pm_qos_add_request(&isp->pm_qos, PM_QOS_CPU_DMA_LATENCY,
              |         ^~~~~~~~~~~~~~~~~~
              |         freq_qos_add_request
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1457:42: error: ‘PM_QOS_CPU_DMA_LATENCY’ undeclared (first use in this function)
         1457 |         pm_qos_add_request(&isp->pm_qos, PM_QOS_CPU_DMA_LATENCY,
              |                                          ^~~~~~~~~~~~~~~~~~~~~~
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1457:42: note: each undeclared identifier is reported only once for each function it appears in
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_v4l2.c:1577:9: error: implicit declaration of function ‘pm_qos_remove_request’; did you mean ‘freq_qos_remove_request’? [-Werror=implicit-function-declaration]
         1577 |         pm_qos_remove_request(&isp->pm_qos);
              |         ^~~~~~~~~~~~~~~~~~~~~
              |         freq_qos_remove_request
]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>

(cherry picked from commit 377c46a378144551ae786450c7ecd55cb61df127)
[ Conflicts:
	drivers/staging/media/atomisp/pci/atomisp2/atomisp_v4l2.c]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>