(FIXME) atomisp: pci: css: avoid va_*() redefined error
What's happening?

        In file included from ./include/linux/kernel.h:5,
                         from ./include/linux/delay.h:22,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/platform_support.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/isp_param/interface/ia_css_isp_param_types.h:19,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/binary/interface/ia_css_binary.h:61,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:23,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        ./include/linux/stdarg.h:6: error: "va_start" redefined [-Werror]
            6 | #define va_start(v, l)  __builtin_va_start(v, l)
              |
        In file included from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:21,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:47: note: this is the location of the previous definition
           47 | #define va_start(v,l)   __builtin_va_start(v,l)
              |
        In file included from ./include/linux/kernel.h:5,
                         from ./include/linux/delay.h:22,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/platform_support.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/isp_param/interface/ia_css_isp_param_types.h:19,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/binary/interface/ia_css_binary.h:61,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:23,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        ./include/linux/stdarg.h:8: error: "va_arg" redefined [-Werror]
            8 | #define va_arg(v, T)    __builtin_va_arg(v, T)
              |
        In file included from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:21,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:49: note: this is the location of the previous definition
           49 | #define va_arg(v,l)     __builtin_va_arg(v,l)
              |
        In file included from ./include/linux/kernel.h:5,
                         from ./include/linux/delay.h:22,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/platform_support.h:24,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/isp_param/interface/ia_css_isp_param_types.h:19,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/binary/interface/ia_css_binary.h:61,
                         from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:23,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        ./include/linux/stdarg.h:9: error: "va_copy" redefined [-Werror]
            9 | #define va_copy(d, s)   __builtin_va_copy(d, s)
              |
        In file included from ./drivers/staging/media/atomisp/pci/atomisp2/css2400/runtime/debug/interface/ia_css_debug.h:21,
                         from drivers/staging/media/atomisp/pci/atomisp2/./css2400/runtime/pipeline/src/pipeline.c:15:
        /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/stdarg.h:52: note: this is the location of the previous definition
           52 | #define va_copy(d,s)    __builtin_va_copy(d,s)
              |

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 78091b2cd8750ba62bf103097d0da33bb75ba10e)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit f5635f355ecb20004bd75e7ec1332cd50131fa34)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 28cea97ec03b5ebc7685e92203d9fff8348d88ce)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit cf08706c026111c9665a65d98fcf3a412bb87ae9)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit b8cf8319adfd064ab63922ecd15a65f9af121a84)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit bba25044896fd9308ef6ce382e293100a09979ef)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 9663c83b6c4e71ea6af68fca23be86bcecba177b)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit e58b8c49c6bb18c465126ede3d87d7a802fa7984)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit ba3e0656b1f20a23cafea74686e682b7a92a9092)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit e42e802fd32368824956098699995c28b88a82c7)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>