(port-to-v5.6) atomisp: micam: atomisp-t4ka3: convert vendorid_proc_fops to "struct proc_ops"
In accordance with commit 97a32539b956 ("proc: convert everything to
struct proc_ops"").

Fixes:

        drivers/staging/media/atomisp/i2c/micam/atomisp-t4ka3.c: In function ‘t4ka3_vendorid_procfs_init’:
        drivers/staging/media/atomisp/i2c/micam/atomisp-t4ka3.c:1442:33: error: passing argument 4 of ‘proc_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
         1442 |                                 &vendorid_proc_fops);
              |                                 ^~~~~~~~~~~~~~~~~~~
              |                                 |
              |                                 const struct file_operations *
        In file included from drivers/staging/media/atomisp/i2c/micam/atomisp-t4ka3.c:39:
        ./include/linux/proc_fs.h:109:122: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
          109 | struct proc_dir_entry *proc_create(const char *name, umode_t mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
              |                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 44ae71a70dc69b167f70992181232a97dba0efbd)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>