(port-to-v4.5) atomisp: i2c: rename entity.type to entity.function
Fixes build errors like the following:

        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c: In function ‘ov5693_probe’:
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:2235:23: error: ‘struct media_entity’ has no member named ‘type’
         2235 |         dev->sd.entity.type = MEDIA_ENT_T_V4L2_SUBDEV_SENSOR;
              |                       ^

in accordance with commit 0e576b76f547 ("[media] media-entity.h: rename
entity.type to entity.function") added on v4.5-rc1.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit ac21e428ff6341794b1848120eff67df09a25614)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit dbdf294cc934ac3c4826e78895cdc0d181d23ad1)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 956d457596ec51890881bd564d8b714c1ab75ab8)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit d8897e02d0d384725f2f53a537f471af4a716431)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>