(port-to-v4.4.167) media: atomisp: replace get_user_pages() write/force parameters with gup_flags
In accordance with commit 8e50b8b0 ("mm: replace get_user_pages()
write/force parameters with gup_flags") and a49d2536 ("staging/atomisp:
Add support for the Intel IPU v2").

Fixes the following build error:

    drivers/media/pci/atomisp/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c: In function ‘alloc_user_pages’:
    drivers/media/pci/atomisp/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1118:65: error: passing argument 7 of ‘get_user_pages’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     1118 |                                          (int)(bo->pgnr), 1, 0, pages,
          |                                                                 ^~~~~
          |                                                                 |
          |                                                                 struct page **
    In file included from drivers/media/pci/atomisp/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:29:
    include/linux/mm.h:1248:45: note: expected ‘struct vm_area_struct **’ but argument is of type ‘struct page **’
     1248 |                     struct vm_area_struct **vmas);
          |                     ~~~~~~~~~~~~~~~~~~~~~~~~^~~~
    drivers/media/pci/atomisp/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:1116:27: error: too many arguments to function ‘get_user_pages’
     1116 |                 page_nr = get_user_pages(current, current->mm,
          |                           ^~~~~~~~~~~~~~
    In file included from drivers/media/pci/atomisp/css2401a0_v21_build/../atomisp_driver/hmm/hmm_bo.c:29:
    include/linux/mm.h:1245:6: note: declared here
     1245 | long get_user_pages(struct task_struct *tsk, struct mm_struct *mm,
          |      ^~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit aefbc2a1f8b98c17a83192a5f6b6de0dfa936ef9)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit c7eaa4533bed96a8f18c3c20dd1fe00e4f261f24)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 56b1b45a3314fe98e99ecb4408212dcd62524a7a)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>