i915: [TEMP-FIX-chromeos-5.4] avoid unused-value error
Somehow the compiler started outputting unused-value error:

    In file included from ./drivers/gpu/drm/i915/gt/intel_engine_types.h:24,
                     from ./drivers/gpu/drm/i915/gt/intel_context_types.h:18,
                     from ./drivers/gpu/drm/i915/gem/i915_gem_context_types.h:20,
                     from ./drivers/gpu/drm/i915/i915_request.h:32,
                     from ./drivers/gpu/drm/i915/i915_active.h:13,
                     from ./drivers/gpu/drm/i915/gem/i915_gem_object_types.h:13,
                     from ./drivers/gpu/drm/i915/display/intel_frontbuffer.h:30,
                     from ./drivers/gpu/drm/i915/i915_drv.h:74,
                     from drivers/gpu/drm/i915/gt/intel_lrc.c:136:
    drivers/gpu/drm/i915/gt/intel_lrc.c: In function ‘intel_context_update_runtime’:
    ./drivers/gpu/drm/i915/i915_selftest.h:118:31: error: statement with no effect [-Werror=unused-value]
      118 | #define I915_SELFTEST_ONLY(x) 0
          |                               ^
    drivers/gpu/drm/i915/gt/intel_lrc.c:1205:3: note: in expansion of macro ‘I915_SELFTEST_ONLY’
     1205 |   I915_SELFTEST_ONLY(ce->runtime.num_underflow += dt < 0);
          |   ^~~~~~~~~~~~~~~~~~
    ./drivers/gpu/drm/i915/i915_selftest.h:118:31: error: statement with no effect [-Werror=unused-value]
      118 | #define I915_SELFTEST_ONLY(x) 0
          |                               ^
    drivers/gpu/drm/i915/gt/intel_lrc.c:1206:3: note: in expansion of macro ‘I915_SELFTEST_ONLY’
     1206 |   I915_SELFTEST_ONLY(ce->runtime.max_underflow =
          |   ^~~~~~~~~~~~~~~~~~

For now, avoid this by adding a new function that just returns 0.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>