(temp-fix) atomisp: pci: make csi_rx_private.h inline functions non-static
Fixes errors like the following:

        ./drivers/staging/media/atomisp/pci/atomisp2/css2400/css_2401_csi2p_system/host/csi_rx_private.h:37:20: error: static declaration of ‘csi_rx_fe_ctrl_get_state’ follows non-static declaration
           37 | static inline void csi_rx_fe_ctrl_get_state(
              |                    ^~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 000c3dda4953acc42af1494ac01611bc46d04bdc)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>