(TEMP) (revert-for->=-v4.14) Revert "fs: unexport vfs_read and vfs_write"
This reverts commit bd8df82be66698042d11e7919e244c8d72b042ca.

There are two users of vfs_write():

        ./drivers/staging/media/atomisp/i2c/micam/dw9761.c:	vfs_write(fp, pData, size, &pos);
        ./drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:	vfs_write(fp, pData, size, &pos);

Convert to drop vfs_write() later.

These commits may help understand what needs to be done:

  - 05a4a33b6d82 ("gadget/f_mass_storage: stop messing with the address limit")
  - 9a779bc149c7 ("serial2002: switch serial2002_tty_write to kernel_{read/write}")
  - 8a2af06415ef ("ashmem: switch to ->read_iter")
  - 8257723993e2 ("lustre: switch to kernel_write")

Address the following:

          MODPOST 3921 modules
        ERROR: "vfs_write" [drivers/staging/media/atomisp/i2c/micam/atomisp-t4ka3drv.ko] undefined!
        ERROR: "vfs_write" [drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.ko] undefined!
        make[1]: *** [scripts/Makefile.modpost:92: __modpost] Error 1

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 467934f63711c6f7df19be4d85b91bcbfa673bdb)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit c56d67b6787679a2a860ba1c1305886846346e50)
[ Conflicts:
	fs/read_write.c]
[while here, removed unneeded new lines above EXPORT_SYMBOL()]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>