(partial-pick-upst-v5.8) atomisp: fix typo V4L2_CID_VCM_TIMEING -> V4L2_CID_VCM_TIMING
Picked this change to build upstream sensor drivers.
Ref: abbd669dbfbb ("media: atomisp: do another round of coding style cleanup")

Fixes:

        drivers/staging/media/atomisp/i2c/ov5693/atomisp-ov5693.c: In function ‘ov5693_s_ctrl’:
        drivers/staging/media/atomisp/i2c/ov5693/atomisp-ov5693.c:1091:14: error: ‘V4L2_CID_VCM_TIMING’ undeclared (first use in this function); did you mean ‘V4L2_CID_VCM_TIMEING’?
         1091 |         case V4L2_CID_VCM_TIMING:
              |              ^~~~~~~~~~~~~~~~~~~
              |              V4L2_CID_VCM_TIMEING
        drivers/staging/media/atomisp/i2c/ov5693/atomisp-ov5693.c:1091:14: note: each undeclared identifier is reported only once for each function it appears in
        drivers/staging/media/atomisp/i2c/ov5693/atomisp-ov5693.c: At top level:
        drivers/staging/media/atomisp/i2c/ov5693/atomisp-ov5693.c:1234:23: error: ‘V4L2_CID_VCM_TIMING’ undeclared here (not in a function); did you mean ‘V4L2_CID_VCM_TIMEING’?
         1234 |                 .id = V4L2_CID_VCM_TIMING,
              |                       ^~~~~~~~~~~~~~~~~~~
              |                       V4L2_CID_VCM_TIMEING

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>