(patch-fixup) usb: dwc3: fixup patch applied to wrong place
The previous patch 632e5029 ("usb: otg: add cherryview support") applied
to a wrong place accidentally.

Fixes the following build errors:

    drivers/usb/dwc3/gadget.c: In function ‘dwc3_gadget_stop’:
    drivers/usb/dwc3/gadget.c:1735:17: error: ‘ret’ undeclared (first use in this function); did you mean ‘net’?
     1735 |                 ret = otg_set_peripheral(dwc->usb2_phy->otg, &dwc->gadget);
          |                 ^~~
          |                 net
    drivers/usb/dwc3/gadget.c:1735:17: note: each undeclared identifier is reported only once for each function it appears in
    drivers/usb/dwc3/gadget.c:1739:25: error: label ‘err0’ used but not defined
     1739 |                         goto err0;
          |                         ^~~~
    make[3]: *** [scripts/Makefile.build:280: drivers/usb/dwc3/gadget.o] Error 1

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>