(WIP) pmic: crystalcove: trying to fix driver loading caused by whiskeycove driver
The crystalcove pmic on Microsoft Surface 3 is still not working:

        [    8.226541] intel_soc_pmic_exec_mipi_pmic_seq_element: No PMIC registered
        [    8.226543] intel_soc_pmic_exec_mipi_pmic_seq_element: No PMIC registered
        [    8.247080] intel_soc_pmic_exec_mipi_pmic_seq_element: No PMIC registered
        [    8.247089] intel_soc_pmic_exec_mipi_pmic_seq_element: No PMIC registered

Tuerned out that the whiskeycove patches from aero caused this issue.

I hoped adding

        static struct acpi_device_id pmic_acpi_match[] = {
        	{ "INT34D3", (kernel_ulong_t)&whiskey_cove_pmic},
        +	{ "INT33FD", (kernel_ulong_t)&crystal_cove_pmic},
        	{ },
        };

just worked, but turned out the definition of crystal_cove_pmic is
missing. Next work is to add the definition. WIP.

Build error message:

          LD      init/built-in.o
        ld: drivers/built-in.o:(.data+0x1af30): undefined reference to `crystal_cove_pmic'
        make: *** [Makefile:992: vmlinux] Error 1

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>