atomisp: Fix -Werror=int-in-bool-context compile errors
With gcc-7.1.1 I was getting the following compile error:

error: ‘*’ in boolean context, suggest ‘&&’ instead

The problem is the definition of CEIL_DIV:
 #define CEIL_DIV(a, b)       ((b) ? ((a) + (b) - 1) / (b) : 0)

Which when called as: CEIL_DIV(x, y * z) triggers this error, note
we cannot do as the error suggests since b is evaluated multiple times.

This commit fixes these compile errors.

Signed-off-by: Hans de Goede <hdegoede@redhat.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>

(cherry picked from commit 02d978318b0983e7af6bbc9c1f9861b0d6983e37)
[ Conflicts:
	drivers/staging/media/atomisp/pci/css/hive_isp_css_include/math_support.h
 due to "#ifdef ISP2401" not exist here]
[Fixes the following build error:

        In file included from drivers/staging/media/atomisp/pci/css2401a0_v21_build/../css/./sh_css_internal.h:19,
                         from drivers/staging/media/atomisp/pci/css2401a0_v21_build/../css/./sh_css.c:21:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../css/./sh_css.c: In function ‘load_video_binaries’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../css/./sh_css.c:5914:73: error: ‘*’ in boolean context, suggest ‘&&’ instead [-Werror=int-in-bool-context]
         5914 |                          (mycs->video_binary.info->sp.block.block_width * ISP_NWAY));
        ./drivers/staging/media/atomisp/pci/css2401a0_v21_build/../css/./hive_isp_css_include/math_support.h:63:32: note: in definition of macro ‘CEIL_DIV’
           63 | #define CEIL_DIV(a, b)       ((b) ? ((a) + (b) - 1) / (b) : 0)
              |                                ^
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../css/./sh_css.c:5913:25: note: in expansion of macro ‘CEIL_MUL’
         5913 |                         CEIL_MUL(tnr_width,
              |                         ^~~~~~~~
        cc1: all warnings being treated as errors

 For the record, here is the code excerpt where the compiler pointed out:

 # from drivers/staging/media/atomisp/pci/css2401a0_v21_build/../css/./sh_css.c
	/* Make tnr reference buffers output block width(in pix) align */
	tnr_info.res.width  =
		CEIL_MUL(tnr_width,
		 (mycs->video_binary.info->sp.block.block_width * ISP_NWAY));
]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>

(cherry picked from commit 037f296ee651573d0bfe37b99fc39a005040cd93)
[ Conflicts:
	drivers/staging/media/atomisp/pci/atomisp2/css2400/hive_isp_css_include/math_support.h]
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>