(WIP?) (port-to-v4.19) atomisp: Convert to new IDA API
The old ida_remove() and ida_get_new_above() was removed on commit
b03f8e43c926 ("ida: Remove old API"). So, convert to use new API.

Ref:
- mchehab/experimental.git - Mauro's development stuff
  https://git.linuxtv.org/mchehab/experimental.git/commit/?h=yocto_intel_aero_ported_v2&id=2616c5667872506e07ac7b0549ddb049697ff200
  ("media: atomisp: make Yocto's version build with Kernel 5.7")
- 3aed4bc1e591 ("mtip32xx: Convert to new IDA API")
- 5a2ab034396c ("media: Convert entity ID allocation to new IDA API")
- b3fa64170e21 ("ppc: Convert mmu context allocation to new IDA API")

WIP (?):
  Where is the mutex_lock() or spin_lock() got like the onther drivers
  in Ref above?

Fixes like:

        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_acc.c: In function ‘atomisp_acc_release’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_acc.c:133:17: error: implicit declaration of function ‘ida_remove’; did you mean ‘idr_remove’? [-Werror=implicit-function-declaration]
          133 |                 ida_remove(&asd->acc.ida, acc_fw->handle);
              |                 ^~~~~~~~~~
              |                 idr_remove
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_acc.c: In function ‘atomisp_acc_load_to_pipe’:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_acc.c:184:13: error: implicit declaration of function ‘ida_get_new_above’ [-Werror=implicit-function-declaration]
          184 |             ida_get_new_above(&asd->acc.ida, 1, &handle)) {
              |             ^~~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 9187fee457c412ae2834da4aff406a2e573565f6)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>