(port-to-v4.5) atomisp: convert links of struct media_link from array to list
In accordance with commit 57208e5e25f2 ("[media] media: convert links
from array to list").

Fixes the following build error:

	drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c: In function ‘atomisp_subdev_source_pad’:
	drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c:149:34: error: subscripted value is neither array nor pointer nor vector
	  149 |         return vdev->entity.links[0].source->index;
	      |                                  ^
	drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c:150:1: error: control reaches end of non-void function [-Werror=return-type]
	  150 | }
	      | ^

Ref:
- mchehab/experimental.git - Mauro's development stuff
  https://git.linuxtv.org/mchehab/experimental.git/commit/?h=yocto_intel_aero_ported_v2&id=2616c5667872506e07ac7b0549ddb049697ff200
  ("media: atomisp: make Yocto's version build with Kernel 5.7")

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit e73727a88c39d3e93b6aa66d6bb2d3c2097111e9)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 68b9a8e1aedc04c6fc54a755acd2cfa360f07834)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>