surface_sam: ssh: add __maybe_unused to unused functions
To supress the following build warn/error:

    drivers/platform/x86/surface_sam/surface_sam_ssh.c:3793:12: error: ‘ssam_nf_unregister’ defined but not used [-Werror=unused-function]
     3793 | static int ssam_nf_unregister(struct ssam_nf *nf, struct ssam_event_notifier *n)
          |            ^~~~~~~~~~~~~~~~~~
    drivers/platform/x86/surface_sam/surface_sam_ssh.c:3766:12: error: ‘ssam_nf_register’ defined but not used [-Werror=unused-function]
     3766 | static int ssam_nf_register(struct ssam_nf *nf, struct ssam_event_notifier *n)
          |            ^~~~~~~~~~~~~~~~
    drivers/platform/x86/surface_sam/surface_sam_ssh.c:2233:12: error: ‘ssh_ptl_flush’ defined but not used [-Werror=unused-function]
     2233 | static int ssh_ptl_flush(struct ssh_ptl *ptl, unsigned long timeout)
          |            ^~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>