(TEMP) (revert-for->=v4.17) Revert "media: v4l2-subdev.h: remove obsolete g/s_parm"
This reverts commit 8180b4f4f589ee34d698d30ae6ad7042bf7ff1a0.

Atomisp drivers in this tree is not converted yet. Convert them later.

Addresses like:

        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c: At top level:
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:2134:10: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘g_parm’
         2134 |         .g_parm = ov5693_g_parm,
              |          ^~~~~~
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:2134:19: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_fract *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_streamparm *)’ [-Werror=incompatible-pointer-types]
         2134 |         .g_parm = ov5693_g_parm,
              |                   ^~~~~~~~~~~~~
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:2134:19: note: (near initialization for ‘ov5693_video_ops.g_pixelaspect’)
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:2135:10: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘s_parm’
         2135 |         .s_parm = ov5693_s_parm,
              |          ^~~~~~
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:2135:19: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_frame_interval *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_streamparm *)’ [-Werror=incompatible-pointer-types]
         2135 |         .s_parm = ov5693_s_parm,
              |                   ^~~~~~~~~~~~~

        In file included from drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_cmd.h:31,
                         from drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c:32:
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c: In function ‘__atomisp_update_run_mode’:
        ./include/media/v4l2-subdev.h:1130:56: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘s_parm’
         1130 |                 else if (!((sd)->ops->o && (sd)->ops->o->f))            \
              |                                                        ^~
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c:1139:16: note: in expansion of macro ‘v4l2_subdev_call’
         1139 |         return v4l2_subdev_call(
              |                ^~~~~~~~~~~~~~~~
        ./include/media/v4l2-subdev.h:1133:48: error: ‘const struct v4l2_subdev_video_ops’ has no member named ‘s_parm’
         1133 |                         __result = (sd)->ops->o->f((sd), ##args);       \
              |                                                ^~
        drivers/staging/media/atomisp/pci/css2401a0_v21_build/../atomisp_driver/atomisp_subdev.c:1139:16: note: in expansion of macro ‘v4l2_subdev_call’
         1139 |         return v4l2_subdev_call(
              |                ^~~~~~~~~~~~~~~~

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 21d7e6e685339d8904792b35dd03fb717d247ac9)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>