(port-to-v4.5) atomisp: i2c: Rename entities types to functions
MEDIA_ENT_T_V4L2_SUBDEV_SENSOR -> MEDIA_ENT_F_CAM_SENSOR

in accordance with commit 4ca72efaeffd ("[media] uapi/media.h: Rename
entities types to functions") added on v4.5-rc1.

Fixes build errors like the following:

        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c: In function ‘ov5693_probe’:
        drivers/staging/media/atomisp/i2c/micam/atomisp-ov5693.c:2235:35: error: ‘MEDIA_ENT_T_V4L2_SUBDEV_SENSOR’ undeclared (first use in this function); did you mean ‘MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN’?
         2235 |         dev->sd.entity.function = MEDIA_ENT_T_V4L2_SUBDEV_SENSOR;
              |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              |                                   MEDIA_ENT_F_V4L2_SUBDEV_UNKNOWN

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 849e8573c09d393ddfc6bb49a08d8fc16bf2144e)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 6c75d0a8741a246e7c8c8d61d25d99a911ac7530)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 7d4843bc72cc71a6bea07729e7d13cf6e3151987)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 7fbd722326910776d9924cb20d693955c285b237)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 69009a2d08df458f468a27ce6ef1e375c8a17f48)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>