(for-v4.4) mfd/intel_soc_pmic_chtwc.c: add seemingly missing module.h header
Fixes the following build error:

          CC [M]  drivers/mfd/intel_soc_pmic_chtwc.o
        In file included from include/linux/acpi.h:27,
                         from drivers/mfd/intel_soc_pmic_chtwc.c:14:
        include/linux/device.h:1361:1: warning: data definition has no type or storage class
         1361 | module_init(__driver##_init); \
              | ^~~~~~~~~~~
        include/linux/i2c.h:652:9: note: in expansion of macro ‘module_driver’
          652 |         module_driver(__i2c_driver, i2c_add_driver, \
              |         ^~~~~~~~~~~~~
        drivers/mfd/intel_soc_pmic_chtwc.c:232:1: note: in expansion of macro ‘module_i2c_driver’
          232 | module_i2c_driver(cht_wc_driver);
              | ^~~~~~~~~~~~~~~~~
        include/linux/device.h:1361:1: error: type defaults to ‘int’ in declaration of ‘module_init’ [-Werror=implicit-int]
         1361 | module_init(__driver##_init); \
              | ^~~~~~~~~~~
        include/linux/i2c.h:652:9: note: in expansion of macro ‘module_driver’
          652 |         module_driver(__i2c_driver, i2c_add_driver, \
              |         ^~~~~~~~~~~~~
        drivers/mfd/intel_soc_pmic_chtwc.c:232:1: note: in expansion of macro ‘module_i2c_driver’
          232 | module_i2c_driver(cht_wc_driver);
              | ^~~~~~~~~~~~~~~~~
        drivers/mfd/intel_soc_pmic_chtwc.c:232:1: warning: parameter names (without types) in function declaration
        In file included from include/linux/acpi.h:27,
                         from drivers/mfd/intel_soc_pmic_chtwc.c:14:
        include/linux/device.h:1366:1: warning: data definition has no type or storage class
         1366 | module_exit(__driver##_exit);
              | ^~~~~~~~~~~
        include/linux/i2c.h:652:9: note: in expansion of macro ‘module_driver’
          652 |         module_driver(__i2c_driver, i2c_add_driver, \
              |         ^~~~~~~~~~~~~
        drivers/mfd/intel_soc_pmic_chtwc.c:232:1: note: in expansion of macro ‘module_i2c_driver’
          232 | module_i2c_driver(cht_wc_driver);
              | ^~~~~~~~~~~~~~~~~
        include/linux/device.h:1366:1: error: type defaults to ‘int’ in declaration of ‘module_exit’ [-Werror=implicit-int]
         1366 | module_exit(__driver##_exit);
              | ^~~~~~~~~~~
        include/linux/i2c.h:652:9: note: in expansion of macro ‘module_driver’
          652 |         module_driver(__i2c_driver, i2c_add_driver, \
              |         ^~~~~~~~~~~~~
        drivers/mfd/intel_soc_pmic_chtwc.c:232:1: note: in expansion of macro ‘module_i2c_driver’
          232 | module_i2c_driver(cht_wc_driver);
              | ^~~~~~~~~~~~~~~~~
        drivers/mfd/intel_soc_pmic_chtwc.c:232:1: warning: parameter names (without types) in function declaration
        In file included from include/linux/acpi.h:27,
                         from drivers/mfd/intel_soc_pmic_chtwc.c:14:
        drivers/mfd/intel_soc_pmic_chtwc.c:232:19: warning: ‘cht_wc_driver_exit’ defined but not used [-Wunused-function]
          232 | module_i2c_driver(cht_wc_driver);
              |                   ^~~~~~~~~~~~~
        include/linux/device.h:1362:20: note: in definition of macro ‘module_driver’
         1362 | static void __exit __driver##_exit(void) \
              |                    ^~~~~~~~
        drivers/mfd/intel_soc_pmic_chtwc.c:232:1: note: in expansion of macro ‘module_i2c_driver’
          232 | module_i2c_driver(cht_wc_driver);
              | ^~~~~~~~~~~~~~~~~
        drivers/mfd/intel_soc_pmic_chtwc.c:232:19: warning: ‘cht_wc_driver_init’ defined but not used [-Wunused-function]
          232 | module_i2c_driver(cht_wc_driver);
              |                   ^~~~~~~~~~~~~
        include/linux/device.h:1357:19: note: in definition of macro ‘module_driver’
         1357 | static int __init __driver##_init(void) \
              |                   ^~~~~~~~
        drivers/mfd/intel_soc_pmic_chtwc.c:232:1: note: in expansion of macro ‘module_i2c_driver’
          232 | module_i2c_driver(cht_wc_driver);
              | ^~~~~~~~~~~~~~~~~
        cc1: some warnings being treated as errors
        make[1]: *** [scripts/Makefile.build:286: drivers/mfd/intel_soc_pmic_chtwc.o] Error 1
        make: *** [Makefile:1453: _module_drivers/mfd] Error 2

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
(cherry picked from commit 6af95f8a9b6c6ec9f48486e4b3619a59e5ce5c9c)
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>