atomisp: Kconfig: update from v5.14-rc4
Now build fails if PMIC_OPREGION is not set:

          LD      init/built-in.o
        ld: arch/x86/built-in.o: in function `gmin_i2c_write':
        atomisp_gmin_platform.c:(.text+0x7103c): undefined reference to `intel_soc_pmic_exec_mipi_pmic_seq_element'
        make: *** [Makefile:992: vmlinux] Error 1

and also depends on CONFIG_CRC_PMIC_OPREGION to actually use the function
intel_soc_pmic_exec_mipi_pmic_seq_element().
Code in atomisp_gmin_platform.c says:

        ret = intel_soc_pmic_exec_mipi_pmic_seq_element(i2c_addr, reg, value, mask);
        if (ret == -EOPNOTSUPP)
        	dev_err(dev,
        		"ACPI didn't mapped the OpRegion needed to access I2C address 0x%02x.\n"
        		"Need to compile the kernel using CONFIG_*_PMIC_OPREGION settings\n",
        		i2c_addr);

So, let's add PMIC_OPREGION and CRC_PMIC_OPREGION as dependency.

While here, lets update the Kconfig in accordance with the upstream one.
There is no config INTEL_ATOMISP in this kernel tree, so, I added all to
VIDEO_ATOMISP. Also , I guess atomisp is useless without INTEL_MID_ISP.
So, also add it as dependency.

Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>